goplus/builder

- docs/Upload and Save.md
feat:Create Upload and Save.md
> Create Upload and Save.md

- spx-gui/src/App.vue
- spx-gui/src/api/asset.ts
- spx-gui/src/api/project.ts
- spx-gui/src/axios/index.ts
- spx-gui/src/class/AssetBase.ts
- spx-gui/src/class/backdrop.ts
- spx-gui/src/class/sound.ts
- spx-gui/src/class/sprite.ts
- spx-gui/src/components/sounds/SoundsEdit.vue
- spx-gui/src/components/sounds/SoundsEditCard.vue
- spx-gui/src/components/sounds/SoundsHome.vue
- spx-gui/src/components/sprite-list/BackdropList.vue
- spx-gui/src/components/sprite-list/SpriteAddBtn.vue
- spx-gui/src/components/sprite-list/SpriteList.vue
- spx-gui/src/components/spx-library/LibraryModal.vue
- spx-gui/src/components/spx-stage/Sprite.vue
- spx-gui/src/components/top-menu/TopMenu.vue
- spx-gui/src/interface/file.ts
- spx-gui/src/language/index.ts
- spx-gui/src/main.ts
- spx-gui/src/plugins/code-editor/index.ts
- spx-gui/src/router/index.ts
- spx-gui/src/store/index.ts
- spx-gui/src/store/modules/project/index.ts
- spx-gui/src/util/store.ts
- spx-gui/tsconfig.app.json
- spx-gui/tsconfig.json
- spx-gui/tsconfig.node.json
`tsconfig.json` has been updated to match the official Vue template.
There are two main types of issue arose because of the change of compiler rules.
- Imports end with `.ts` which is redundant. Already fixed in the PR.
- Type only imports should be used: `import type ... from ...`
Until the type only imports are fixed, the project will not run (white screen only).
> Update tsconfig.json & fix part of type errors

- spx-gui/.eslintrc.cjs
- spx-gui/package.json
Fix error on running `npm run lint`:
```
Error: Error while loading rule '@typescript-eslint/naming-convention': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Note: detected a parser other than @typescript-eslint/parser. Make sure the parser is configured to forward "parserOptions.project" to @typescript-eslint/parser.
```
> fix error on `npm run lint` & format

- spx-gui/src/class/backdrop.ts
- spx-gui/src/components/stage-viewer-demo/StageViewerDemo.vue
- spx-gui/src/components/stage-viewer/SpriteLayer.vue
- spx-gui/src/interface/file.ts
- spx-gui/src/store/modules/backdrop/index.ts
- spx-gui/src/store/modules/project/index.ts
- spx-gui/src/store/modules/sprite/index.ts
#124
In each item of zorder, in addition to the Sprite name provided as a string, there is an item configuration like stageMonitor configured as an object,So the item type of zorder has been changed to `Array<string|Object>` to avoid unexpected runtime type errors
```json
{
"zorder": [
"calf",
{
"type": "stageMonitor",
"target": "Dragon",
"val": "getVar:score",
"color": 15629590,
"label": "score",
"mode": 1,
"x": 5,
"y": 5,
"visible": true
}
]
}
```
> feat:modify the zorder update logic

- spx-gui/src/components/spx-stage/SpxStage.vue
The current zorder config can be updated according to the addition and deletion of sprite, and the defaultBackdrop set before running can be removed.
> chore:remove default backdrop config when run trigger

- spx-gui/src/components/sprite-list/AssetAddBtn.vue
#135
spx code is go+ code, and the sprite name will compiled to an identifier of go+, so sprite name rules is depend on the identifier rules of go+.
> feat:prevent unexpected sprite naming

- nginx.conf
Previous config of client_max_body_size in server {} did not seem to take effect. We move the config to location /api block and it worked in local test.
> fix: modify body size in nginx.conf for /api

- spx-gui/src/components/sprite-list/AssetAddBtn.vue
- spx-gui/src/components/spx-library/LibraryModal.vue
- spx-gui/src/components/spx-library/SpriteCard.vue
Fixed the problem of importing multi-style sprites from the asset library to the sprite list, but unable to switch shapes during runtime.
> fix: unable to switch shapes during multi-style sprites runtime

- .github/workflows/validate.yml
- Dockerfile
- spx-gui/package-lock.json
- spx-gui/package.json
Same tool version for dev, CI & CD:
* Node.js: `^20.11.1` (Latest LTS)
* Go: `^1.21.3` (Currently using version)
TODO:
>  fix version for node & go

- Dockerfile
Path for spx-backend cmd source code is changed in https://github.com/goplus/builder/pull/226. We adjust the path in Dockerfile correspondingly.
> fix path in Dockerfile

- spx-gui/.vscode/extensions.json
`vscode-typescript-vue-plugin` has been deprecated as `volar` is updated to v2.
> update vscode ext recommendations

- spx-gui/src/utils/i18n/index.ts
Use 
```ts
declare module '@vue/runtime-core'
```
instead of 
```ts
declare module 'vue'
```
Related issue: https://github.com/vuejs/language-tools/issues/3372
> Fix type declaration for i18n

- spx-gui/.eslintrc.cjs
- spx-gui/src/apis/common/client.ts
- spx-gui/src/components/editor/EditorContextProvider.vue
- spx-gui/src/components/editor/EditorHomepage.vue
- spx-gui/src/components/editor/panels/sprite/SpriteItem.vue
- spx-gui/src/components/editor/panels/stage/StagePanel.vue
- spx-gui/src/components/editor/panels/todo/AssetAddBtn.vue
- spx-gui/src/components/editor/preview/stage-viewer/BackdropLayer.vue
- spx-gui/src/components/editor/preview/stage-viewer/Costume.vue
- spx-gui/src/components/project/ProjectCreate.vue
- spx-gui/src/models/common/cloud.ts
- spx-gui/src/models/common/disposable.ts
- spx-gui/src/models/common/file.ts
- spx-gui/src/models/costume.ts
- spx-gui/src/models/sound.ts
- spx-gui/src/models/sprite.ts
- spx-gui/src/utils/file.ts
- spx-gui/src/utils/path.test.ts
- spx-gui/src/utils/path.ts
Hooks to help consume URL of class `File`, taking care of:
* Async procedure
* Object URL revoke
It is already disabled for `.ts` files, while not disabled for `.vue` files. Related:
* `@vue/eslint-config-typescript` extends `plugin:@typescript-eslint/eslint-recommended`: [code](https://github.com/vuejs/eslint-config-typescript/blob/e0bf9da6f8a7980f33b6ee4558cc0199fe9eae2c/index.js#L29)
* `plugin:@typescript-eslint/eslint-recommended` disables `no-redeclare` (and other rules which are not needed for Typescript code): [code](https://github.com/typescript-eslint/typescript-eslint/blob/074310029694f92323d4d91f0fd31df39698d0e7/packages/eslint-plugin/src/configs/eslint-recommended-raw.ts#L33)
* while `@vue/eslint-config-typescript` didn't disable `no-redeclare`: …
> Fix some todos

- Dockerfile
- spx-backend/internal/utils/fmtcode/fmtcode.go
Go/Go+ tools are required for spx-backend (API `/util/fmt`) to run.
We need to get rid of such "runtime-binary-dependency" in the future.
> include go/go+ tools in result docker image

- spx-gui/src/components/editor/EditorContextProvider.vue
- spx-gui/src/components/top-nav/TopNav.vue
- spx-gui/src/components/ui/UIButton.vue
- spx-gui/src/components/ui/UIIconButton.vue
- spx-gui/src/components/ui/global.scss
- spx-gui/src/components/ui/menu/UIMenuItem.vue
- spx-gui/src/components/ui/modal/UIFormModal.vue
* Fix state loss when sprite / sound renamed, close #373 
* Fix non-centered modal title, related: #394
* Fix default `font-family` for `button`
> Fix state loss when sprite / sound renamed

- spx-gui/package-lock.json
- spx-gui/package.json
- spx-gui/src/components/editor/code-editor/code-text-editor/CodeTextEditor.vue
- spx-gui/src/components/editor/code-editor/code-text-editor/initialization.ts
- spx-gui/src/components/top-nav/TopNav.vue
通过`@monaco-editor/loader`从CDN导入monaco代码，在导入前配置及下载语言包。导入只会跑一次，导致语言初始化后不会更新。
> monaco i18n

- spx-gui/src/components/asset/scratch/LoadFromScratch.vue
- spx-gui/src/components/asset/scratch/SoundItem.vue
- spx-gui/src/components/editor/panels/sound/SoundsPanel.vue
- spx-gui/src/components/editor/panels/sprite/SpritesPanel.vue
- spx-gui/src/components/editor/panels/stage/StagePanel.vue
- spx-gui/src/components/editor/sound/DumbSoundPlayer.vue
- spx-gui/src/components/editor/sound/SoundEditor.vue
- spx-gui/src/components/editor/sound/SoundPlayer.vue
- spx-gui/src/components/editor/sound/SoundRecorder.vue
- spx-gui/src/components/project/ProjectCreateModal.vue
- spx-gui/src/components/ui/UIButton.vue
- spx-gui/src/components/ui/UIIconButton.vue
- spx-gui/src/components/ui/icons/UIIcon.vue
- spx-gui/src/components/ui/modal/UIFormModal.vue
- spx-gui/src/components/ui/modal/UISearchableModal.vue
- spx-gui/src/models/backdrop.ts
- spx-gui/src/models/costume.ts
- spx-gui/src/models/sound.ts
- spx-gui/src/utils/audio.ts
- spx-gui/src/utils/file.ts
- spx-gui/src/utils/img.ts
- spx-gui/src/utils/scratch.ts
- spx-gui/src/utils/spx.ts
* Fix audio & image support, close #370
* Move spinning animation from `UIButton loading` to `UIIcon type=loading`
* Fix `mask-closable` behavior for `UIFormModal` & `UISearchableModal`
Builder 对于音频 & 图片格式的支持需要考虑两个方面：
1. SPX 的支持情况：决定游戏是否可运行
2. 当前浏览器的支持情况（主要是 decode）：决定资源是否可以在 Builder 中被操作，包括但不限于
* 通过 `SoundPlayer` 播放音频
* 通过 wavesurfer 渲染音轨
* 通过 `StageViewer` 渲染（sprite、backdrop 中的）图片
* 在 `SpritesPanel`、`StagePanel` 中渲染图片
整体的处理方案是：
* 当向项目中添加资源（包括上传、从 scratch 导入等）时，允许的用户输入以当前浏览器的支持情况为准
* 然后检查资源是否被 SPX 支持；若支持，则直接使用；若不支持，将其转换为 SPX 支持的格式再使用
注意，因为当前浏览器原生支持 decode 用户输入的资源，因此我们“几乎”总是可以将其低成本地转换为 SPX 支持的格式（自己搞定 encode 过程即可）
对于以下两种“添加资源”的场景：
* 导入项目文件（这个项目文件可以认为是由 Builder 自己生成的）
* 从素材库添加
这两种情况下，资源的源文件可以认为在最初已经被 Builder 处理过（一定是 SPX 已经支持的），因此不需要走上述的处理过程
不难发现，上述的处理过程基本能保证最终项目中使用的资源是 SPX …
> Fix audio & image support

- spx-gui/src/components/editor/code-editor/code-text-editor/CodeTextEditor.vue
```
Failed to load message bundle for language en. Falling back to the default language: Error: [object Event]
```
> UI: Fix bug where Monaco Editor fails to load 'en' language pack

- spx-gui/src/components/project/runner/IframeDisplay.vue
- spx-gui/src/components/ui/modal/UIFullScreenModal.vue
fix #457 
* Disable auto-focus for `UIFullScreenModal`
* In `IframeDisplay`, wait for `wasmReady` & then focus to canvas
> Fix auto-focus for project-runner

- spx-gui/src/components/editor/panels/sprite/SpriteRenameModal.vue
- spx-gui/src/components/editor/sound/SoundRenameModal.vue
- spx-gui/src/components/project/ProjectCreateModal.vue
- spx-gui/src/components/ui/UITextInput.vue
- spx-gui/src/components/ui/form/UIForm.vue
- spx-gui/src/components/ui/form/UIFormItem.vue
- spx-gui/src/components/ui/form/UIFormItemInternal.vue
- spx-gui/src/components/ui/form/ctrl.ts
* Add success feedback for name input, close #471 
* Implement form validation instead of relying on validation of `NForm` (Validation of `NForm` does not support success feedback)
* Update `UITextInput` error style for design change
> Success feedback for name input

- spx-gui/src/components/project/runner/ProjectRunner.vue
- spx-gui/src/components/top-nav/TopNav.vue
- spx-gui/src/models/common/gbp.ts
- spx-gui/src/models/common/zip.ts
- spx-gui/src/models/project.ts
https://github.com/goplus/builder/issues/464
> use `.gbp` instead of `.zip` for exported projects

- spx-gui/package-lock.json
- spx-gui/package.json
- spx-gui/src/components/editor/preview/stage-viewer/StageViewer.vue
- spx-gui/src/models/stage.ts
- spx-gui/src/utils/path.test.ts
- spx-gui/src/utils/path.ts
* Fix path `resolve` with `.` / `..`
* Accept `costumes` & `currentCostumeIndex` in stage config
* Fix `StageViewer` loading state for project with no backdrops
> improve compatibility with spx

- spx-gui/src/models/common/asset.ts
- spx-gui/src/models/sprite.ts
Exclude code when sprite added to asset-library
* Code reuse is more complex than image / audio files
* Privacy leak may happen unintentionally
So we exclude code from asset-library by default. Code-reuse for sprites requires further design.
> Exclude code when sprite added to asset-library

- spx-gui/src/components/editor/panels/sprite/SpritesPanel.vue
Expand `SpriteBasicConfig` by default to make it easy to find sprite "rename" button, close #537
> Expand `SpriteBasicConfig` by default

- spx-backend/cmd/spx-backend/get_assets_list.yap
- spx-backend/cmd/spx-backend/gop_autogen.go
- spx-backend/init.sql
- spx-backend/internal/controller/asset.go
- spx-backend/internal/controller/asset_test.go
- spx-backend/internal/model/asset.go
- spx-backend/internal/model/asset_test.go
- spx-gui/src/apis/asset.ts
- spx-gui/src/components/asset/library/AssetAddModal.vue
- spx-gui/src/components/project/ProjectCreateModal.vue
- spx-gui/src/models/common/asset.ts
- spx-gui/src/models/common/cloud.test.ts
- spx-gui/src/models/common/cloud.ts
Fixes #520
---
Execute the following SQL in the test env DB for migration before merging:
```sql
ALTER TABLE `asset` ADD COLUMN `files_hash` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL;
```
> Add duplicate asset check when adding to library

- spx-gui/src/utils/file.ts
300ms is too short, so selecting with file is sometimes considered cancelled.
> Fix file select

- spx-gui/src/components/editor/code-editor/FormatButton.vue
- spx-gui/src/components/editor/preview/EditorPreview.vue
- spx-gui/src/components/ui/UIButton.vue
- spx-gui/src/components/ui/UIButtonGroupItem.vue
- spx-gui/src/components/ui/UIIconButton.vue
close #572 （详见 https://github.com/goplus/builder/issues/572#issuecomment-2151780134 ）
* button 整体高度使用跟其它控件一致的高度（40/32/26px），把 #569 中添加的 4px 去掉
* 对于面板右上角的 button（如 Format、Run），使用 size=medium 而不是 size=small
* 对于 `UIButtonGroupItem`，使用与其它输入控件一致的高度（32px）
此外使用 box-shadow + padding 替代原来的 border 实现，解决 https://github.com/goplus/builder/issues/572#issue-2337298602 这里提到的视觉感受上厚度不一致的问题
> Button Shadow Details

- spx-gui/src/components/asset/library/AssetLibraryModal.vue
- spx-gui/src/components/editor/code-editor/CodeEditor.vue
- spx-gui/src/components/editor/common/EditorItemDetail.vue
- spx-gui/src/components/editor/common/EditorList.vue
- spx-gui/src/components/editor/panels/common/PanelList.vue
- spx-gui/src/components/editor/sprite/CostumeDetail.vue
- spx-gui/src/components/editor/stage/BackdropDetail.vue
- spx-gui/src/components/project/ProjectList.vue
* Fix scrollbar for list
通过省略容器的右 padding 来容纳可能占据空间的 scrollbar，这样当 scrollbar 占据空间（如 windows 或配置了总是显示 scrollbar 的 macos）时，列表元素不会被挤下去，我们可以总是在单行展示固定数量的列表元素
* Fix color for category "Event" in tools
* Fix border-radius for backdrop & costume
* Fix outline for backdrop / costume add button
> Fix ui details

- spx-gui/src/models/project/index.ts
> Hotfix: fix `ProjectRunner` issue with small backdrop

- spx-gui/src/components/editor/sound/SoundRecorder.vue
- spx-gui/src/components/editor/sound/WavesurferWithRange.vue
- spx-gui/src/components/editor/sound/wavesurfer.ts
- spx-gui/src/utils/wavesurfer-record.ts
- The waveform now looks smoother and more stable.
- Performance is improved by using cache when showing waveform in recording.
> smoother waveform

- spx-gui/src/utils/wavesurfer-record.ts
在 #589 我们为了解决波形在停止录制时改变的问题，不在结束时使用`loadBlob`重新加载音频，这导致了以下问题：
* 录制停止后（还没有保存）点击播放不会播放
* 录制停止后选择特定范围再保存，保存的依然是原音频，而不是选定的范围
* 录制停止后调整音量，对应的波形变化不符合预期，另外波形图下方会多出来一个滚动条
这里加回去作为临时解决方案
> load audio after recording

- spx-gui/src/components/editor/panels/EditorPanels.vue
> Fix last-select issue when project switched

- spx-gui/src/models/animation.ts
- spx-gui/src/models/common/asset-name.ts
- spx-gui/src/models/costume.ts
- spx-gui/src/models/project/index.ts
- spx-gui/src/models/sprite.ts
close #608, update #543
* Add definition for model `Animation`
* Add animation related logic in model `Sprite` & `Costume`
* Fix naming check for asset
related: https://github.com/goplus/spx/pull/289 (we need to upgrade spx version for `tools/ispx` after https://github.com/goplus/spx/pull/289 merged)
> Model `Animation`

- spx-gui/src/models/common/asset-name.test.ts
- spx-gui/src/models/common/asset-name.ts
In #614, we updated asset name normalization (`normalizeAssetName`), which causes error when creating new projects —— `normalizeAssetName` will be called with empty `src`.
In this PR we update `normalizeAssetName` to avoid the above error.
> fix normalizeAssetName

- spx-gui/src/components/editor/EditorHomepage.vue
- spx-gui/src/components/editor/panels/sprite/SpriteBasicConfig.vue
- spx-gui/src/components/editor/sound/SoundEditor.vue
- spx-gui/src/components/editor/sprite/CostumeDetail.vue
- spx-gui/src/components/editor/stage/BackdropDetail.vue
- spx-gui/src/components/project/ProjectCreateModal.vue
- spx-gui/src/components/project/index.ts
- spx-gui/src/components/top-nav/TopNav.vue
- spx-gui/src/main.ts
- spx-gui/src/utils/exception.ts
close #475 
* Swallow exceptions (if they are handled) in `useMessageHandle` instead of throw them out. 
Then the runtime (browser, vue, etc.) will not catch them.
Typically we should do message handling (`useMessageHandle`) only in the very end of the action chain. So it's ok for `useMessageHandle` to swallow exceptions and there will be no meaningful output to `return`.
* Add missing message handling
> fix `Cancelled` warning in console

- spx-gui/src/components/editor/sprite/SpriteEditor.vue
- spx-gui/src/components/editor/stage/StageEditor.vue
- spx-gui/src/models/common/cloud.ts
- spx-gui/src/models/project/history.test.ts
- spx-gui/src/models/sprite.ts
- spx-gui/src/models/stage.ts
- Removed the "codeFile" concept from sprite and stage models introduced in #508. Since #617, lazy-loading for plain text files is no longer needed.
- Avoided redundant `parseProjectData` in `@/models/common/cloud.save`.
Fixes #369
> refactor(spx-gui): remove "codeFile" concept and optimize project saving

- spx-gui/src/components/editor/code-editor/code-text-editor/tools/index.ts
- spx-gui/src/components/editor/code-editor/code-text-editor/tools/spx.ts
We will keep `onTouched` hidden as it behaves strangely, until https://github.com/goplus/spx/issues/298 is resolved
> Hide tool `onTouched` for code-editor

- spx-gui/src/components/asset/preprocessing/PreprocessModal.vue
- spx-gui/src/components/editor/code-editor/code-text-editor/tools/index.ts
- spx-gui/src/components/editor/code-editor/code-text-editor/tools/spx.ts
* Update code-editor for animation, update #543 
1. Add animation-related tools, e.g. `step`, & update description for existed tools
2. Add animation definitions of current sprite in `Variable` tools
3. Exclude costume-index related tools or usages
* Fix costume add problem introduced in #614
> Update code-editor for animation

- spx-gui/src/components/editor/sprite/animation/AnimationSettings.vue
- spx-gui/src/models/animation.test.ts
- spx-gui/src/models/animation.ts
- spx-gui/src/models/project/index.ts
- spx-gui/src/models/sprite.ts
- spx-gui/src/utils/test.ts
* Fix animation sound loss on project load
In #634, we tried to
> Fix animation sound issues when sound removed / renamed
by clear field `sound` when we can't find it in `project.sounds`.
While we load animations (in sprites) & sounds concurrently, if animation loaded before corresponding sound, the field `sound` will be cleared by mistake.
We move the logic to model `Project` (just like what we do with sprite removing & renaming) to fix that.
* Fix `AnimationSettings` bg color
> Debug animation sound on project load

- spx-gui/src/components/asset/animation/GroupCostumesModal.vue
- spx-gui/src/components/editor/panels/common/PanelList.vue
- spx-gui/src/components/editor/sprite/AnimationDetail.vue
- spx-gui/src/components/editor/sprite/CheckerboardBackground.vue
- spx-gui/src/components/editor/sprite/animation/AnimationPlayer.vue
- spx-gui/src/models/animation.ts
* Add preview for `GroupCostumesModal`, close #645 
* Adjust `AnimationPlayer` to fit `GroupCostumesModal`
> Add preview for `GroupCostumesModal`

- .github/workflows/build.yml
Our CD system hits the pull rate limit of docker hub, thus migrating to ghcr.io.
> Migrate to ghcr.io

- spx-gui/.eslintrc.cjs
- spx-gui/src/components/asset/animation/GroupCostumesModal.vue
- spx-gui/src/components/asset/library/AssetLibraryModal.vue
- spx-gui/src/components/asset/preprocessing/PreprocessModal.vue
- spx-gui/src/components/editor/preview/stage-viewer/SpriteItem.vue
- spx-gui/src/components/editor/sound/SoundRecorder.vue
- spx-gui/src/components/editor/sound/waveform/WaveformRangeControl.vue
- spx-gui/src/components/editor/sprite/AnimationRemoveModal.vue
- spx-gui/src/widgets/spx-runner/SpxRunner.ce.vue
```bash
$ npm run dev
...
[@vue/compiler-sfc] `defineProps` is a compiler macro and no longer needs to be imported.
[@vue/compiler-sfc] `defineEmits` is a compiler macro and no longer needs to be imported.
```
> spx-gui: remove unnecessary `defineProps` and `defineEmits` imports

- Dockerfile
- scripts/pr-preview.sh
- Updated `Dockerfile`:
- Introduced `ARG`s for base images and custom mirror configs.
- Modified the `CMD` instruction to use `exec` for proper signal handling.
- Updated `scripts/pr-preview.sh`:
- Refined `docker build` command to utilize the newly introduced `ARG`s.
> pr-preview: use mirrors for Go and Node modules downloads during `docker build`

- spx-gui/src/apis/util.test.ts
- spx-gui/src/apis/util.ts
- spx-gui/src/models/common/cloud.ts
- Extended `util.makeObjectUrls` with batching to queue and merge object URL requests.
- Updated `cloud.universalUrlToWebUrl` to use batched processing.
- Refactored `cloud.getFiles` and file creation process to support lazy URL resolution, addressing potential URL expiry issues.
Fixes #653
> spx-gui: implement batched object URL processing and optimize lazy loading

- spx-gui/src/components/ui/block-items/UIEditorSoundItem.vue
- spx-gui/src/components/ui/block-items/UIEditorSpriteItem.vue
There is a wall of warnings in console from Vue saying that the `color` prop of `UlEditorSpriteltem` is required but not provided, even if we have already defined the defaults with `withDefaults`.
> fix required prop warnings

- spx-gui/src/apis/asset.ts
- spx-gui/src/components/asset/library/AssetItem.vue
- spx-gui/src/components/asset/library/AssetLibrary.vue
- spx-gui/src/components/asset/library/AssetLibraryModal.vue
- spx-gui/src/components/asset/library/AssetList.vue
This PR introduces the AssetItem component to replace the three existing asset items in the asset library.
- Added AssetItem component to replace the existing asset items.
- Implemented `Add to Project` button, allowing users to add assets directly from the asset list.
- Added a favorite functionality to the `AssetItem` component.
- Added functionality to show/hide information and actions on the asset item.
- Removed the `select and add asset` functionality from the AssetLibrary.
- The backend API for the favorite functionality has not been implemented yet.
> Introduce AssetItem Component 

- spx-gui/src/apis/aigc.ts
- spx-gui/src/components/asset/library/AIAssetItem.vue
- spx-gui/src/components/asset/library/AssetList.vue
This pull request introduces the AIAssetItem component for displaying AI-generated assets.
The component shows the generating status and preview for AI assets and polls for the AI asset generation status. 
1. AIAssetItem.vue
- Added AIAssetItem.vue for displaying AI assets.
- Shows generating status and preview for AI assets.
- Polls for AI asset generation status.
2. AssetList.vue
- Call generate AI image when search result is not enough.
- Use AIAssetItem component for AI assets.
3. aigc.ts
- Add AI-related APIs and types for asset generation
- Add AiAssetData and other AIGC-related types.
- Add new APIs for AI image and sprite generation (Mock).
- Add new APIs for retrieving AI image generation job status (Mock).
- AIGC API has not been implemented yet. All related API will return a …
> feat(spx-gui): Add AI-generated results to search result

- spx-gui/src/models/project/index.test.ts
- spx-gui/src/models/project/index.ts
fix #714 
In this PR we introduced "builder-only data", which is part of project game data, while intended solely for builders, not for spx.
As a convention, we name such data with prefix `builder_`, e.g., `builder_spriteOrder: string[]`
> Stable order for sprites & sounds

- spx-gui/.env
- spx-gui/src/components/asset/preprocessing/PreprocessModal.vue
- spx-gui/src/utils/env.ts
* Make AIGC features configurable, close #724 
* Detail optimization of `PreprocessModal.vue`
For now there's only one feature that relies on AIGC service: "Remove Background" when adding sprites or costumes with local file.
To disable AIGC-related features when AIGC service isn't ready for production, follow these steps:
1. Configure spx-backend with
```sh
AIGC_ENDPOINT=INVALID_URL
```
2. Configure spx-gui with
```sh
VITE_DISABLE_AIGC=true
```
> Configurable AIGC features

- spx-gui/src/apis/asset.ts
- spx-gui/src/components/asset/library/details/DetailModal.vue
- spx-gui/src/components/asset/library/reviews/AssetRate.vue
This pull request implements asset rate functionality.
- add `getAssetRate` API to retrieve the rate of an asset and `rateAsset` API to rate an asset (Mock)
- Add `AssetRate` component to display the asset rating and provide an modal to rate the asset
- Update the asset details modal for AssetRate component
The rating API is not implemented yet.
Currently, it will return a random rating that follows a normal distribution.
> feat(spx-gui): Add asset rate API and functionality

- spx-gui/src/apis/aigc.ts
- spx-gui/src/components/asset/library/AssetLibrary.vue
- spx-gui/src/components/asset/library/AssetList.vue
- spx-gui/src/components/asset/library/SearchContextProvider.vue
- spx-gui/src/components/asset/library/ai/AIPreviewModal.vue
- spx-gui/src/components/asset/library/ai/AISpriteEditor.vue
- spx-gui/src/utils/exception.ts
This pull request integrates asset history api and did some bug fixes for asset list component.
- Introduced asset history tracking to allow users to view their asset history.
- Disabled AI generation for specific categories such as 'liked', 'history', and 'imported' to prevent unnecessary AI-generated assets.
- Implemented a mechanism to abort AI generation and asset search when search parameters are changed quickly, ensuring outdated data is not displayed.
- Added functionality to export AI assets and integrate them into projects, including mock API for exporting and features to `add to project` and `favorite` AI assets.
- Export API has not been implemented yet. It will return a mock result.
- The `preventing race condition` feature in the `useQuery` hook is disabled by default for …
> Integrates asset history api for asset and ai-asset

- spx-gui/src/components/asset/index.ts
- spx-gui/src/components/asset/preprocessing/PreprocessModal.vue
- spx-gui/src/components/asset/preprocessing/remove-background/RemoveBackground.vue
- spx-gui/src/components/editor/stage/BackdropsEditor.vue
- spx-gui/src/components/ui/message/index.ts
- spx-gui/src/models/common/cloud.ts
- spx-gui/src/models/common/file.ts
- Added loading message type for global loading-feedback.
- Integrated file upload process into `PreprocessModal`'s confirmation for files requiring preprocessing.
- Implemented loading message display for file uploads without preprocessing.
- Ensured resource addition only completes after successful file upload.
- Fixed filename change issue in `PreprocessModal` caused by `RemoveBackground` application.
Fixes #638
> spx-gui: upload files when adding resource

- spx-gui/src/components/asset/library/SpritePreview.vue
- spx-gui/src/components/asset/library/details/BackdropDetailDisplay.vue
- spx-gui/src/components/asset/library/details/DetailModal.vue
- spx-gui/src/components/asset/library/details/SpriteDetailDisplay.vue
This pull request adjusted the style of the asset detail page, and provided a preview of the sprite asset with carousel.
- Updated styles of the asset detail page.
- Updated i18n text for asset info.
- Replaced the single image preview with a carousel component. And added carousel items for animations and custom costumes.
- Implemented thumbnail navigation for the carousel.
- Implemented backdrop preview component and provided image preview, zoom in/out, and drag functionality.
> Enhance asset detail page with carousel and style updates

- spx-gui/src/components/editor/EditorHomepage.vue
- spx-gui/src/components/ui/dialog/UIConfirmDialog.vue
- spx-gui/src/models/project/index.ts
We block route changes when there are unsaved changes using `UIConfirmDialog`. For better UX, an automatic save is triggered when the dialog is mounted, reducing the need for users to manually click the `Save` button. If the save failes, users can simply retry by clicking `Save`.
Fixes #665
> spx-gui: auto save unsaved changes on route change

- spx-gui/src/components/asset/library/AssetList.vue
- spx-gui/src/components/asset/library/details/BackdropDetailDisplay.vue
- spx-gui/src/components/asset/library/details/DetailModal.vue
- spx-gui/src/components/asset/library/details/PreviewController.vue
- spx-gui/src/components/asset/library/details/SoundDetailDisplay.vue
- spx-gui/src/components/editor/sound/waveform/WaveformDisplay.vue
- spx-gui/src/components/editor/sound/waveform/WaveformPlayer.vue
This pull request provides waveform preview for sound assets.
- Added sound asset preview.
- Improved waveform display with dynamic scrolling and zooming.
- Provided playback controls for volume and progress.
> feat: add sound detail display

- spx-gui/src/models/project/index.test.ts
- spx-gui/src/models/project/index.ts
> Fix auto selection after sound removed

- spx-gui/src/components/project/ProjectCreateModal.vue
- spx-gui/src/models/animation.test.ts
- spx-gui/src/models/project/history.ts
- spx-gui/src/models/project/index.test.ts
- spx-gui/src/models/project/index.ts
- spx-gui/src/utils/disposable.ts
- spx-gui/src/utils/exception.ts
> fix(Project): prevent potential data corruption in `saveToCloud` and `saveToLocalCache`

- spx-gui/src/components/asset/library/ai/AIBackdropEditor.vue
- spx-gui/src/components/asset/library/ai/AIPreviewModal.vue
- spx-gui/src/components/asset/library/ai/ImageEditor/ImageCrop.vue
- spx-gui/src/components/asset/library/ai/ImageEditor/ImageResize.vue
- spx-gui/src/components/asset/library/ai/ImageEditor/useCenterPosition.ts
- spx-gui/src/components/asset/library/ai/ImageEditor/useRenderScale.ts
This pull requests implements a backdrop editor for AI generated backdrop, including `resize` and `crop`.
> feat: edit AI-generated backdrop

- spx-gui/src/components/editor/code-editor/EditorUI.ts
- spx-gui/src/components/editor/code-editor/compiler.ts
- spx-gui/src/components/editor/code-editor/coordinators/index.ts
- spx-gui/src/components/editor/code-editor/document.ts
- spx-gui/src/components/editor/code-editor/ui/MarkdownPreview.vue
- spx-gui/src/components/editor/code-editor/ui/code-text-editor/CodeTextEditor.vue
- spx-gui/src/components/editor/code-editor/ui/common/languages/index.ts
- spx-gui/src/components/editor/code-editor/ui/features/completion-menu/completion-menu.ts
- spx-gui/src/components/editor/code-editor/ui/features/hover-preview/DocumentPreview.vue
- spx-gui/src/components/editor/code-editor/ui/features/hover-preview/HoverPreviewComponent.vue
- spx-gui/src/components/editor/code-editor/ui/features/hover-preview/hover-preview.ts
this pr is about refacor some codes for `HoverPreview`
- refactor code from `languages/index.ts` to `MarkdownPreview.vue`
- remove `TokenEnum` protoype， and modify some defination in `compiler.ts`
- make some funcions return type from `LayerContent` to `LayerContent[]` 
- refactor code from `hover-preview.ts` to `HoverPreviewComponent.vue`
> feat(spx-gui): refactor hoverPreivew codes

- tools/ispx/main.go
> Simplify ispx

- spx-gui/src/components/editor/code-editor/ui/features/selection-menu/EditorBulb.vue
- spx-gui/src/components/editor/code-editor/ui/features/selection-menu/SelectionMenuComponent.vue
- spx-gui/src/components/editor/code-editor/ui/features/selection-menu/selection-menu.ts
this pr is about implement `SelectionMenu` action callback, and fix when select content is empty still show suggestions.
> feat(spx-gui): implment `SelecitonMenu` action callback.

- spx-gui/src/components/editor/code-editor/CodeEditor.vue
- spx-gui/src/components/editor/code-editor/EditorUI.ts
- spx-gui/src/components/editor/code-editor/coordinators/index.ts
- spx-gui/src/components/editor/code-editor/ui/code-text-editor/CodeTextEditor.vue
- spx-gui/src/components/editor/code-editor/ui/features/completion-menu/CompletionMenuComponent.vue
- spx-gui/src/components/editor/code-editor/ui/features/completion-menu/completion-item-cache.ts
- spx-gui/src/components/editor/code-editor/ui/features/completion-menu/completion-menu.ts
This PR addresses the issue where the completion menu items are duplicated when repeatedly entering content at the same location. It also fixes the problem where multiple calls to the `addItem` function result in the previous completion menu items being overwritten.
>  fix: patch to fix duplicate display and overwriting issues in completion menu items

- spx-gui/src/apis/common/client.ts
- spx-gui/src/apis/project.ts
- spx-gui/src/models/common/cloud.ts
- spx-gui/src/models/project/index.test.ts
- spx-gui/src/models/project/index.ts
- spx-gui/src/utils/utils.ts
This also improves the auto-save mechanism by making it reactive to the `saveToCloud` process.
Fixes #796
> refactor(Project): abort previous `saveToCloud` before starting a new one

- spx-gui/src/components/editor/code-editor/compiler.ts
this pr is about fix when wasm crashed compiler can not auto reload to recover wasm ability
> fix(spx-gui): fix when wasm crashed compiler can not auto recover

- spx-gui/src/components/editor/code-editor/EditorUI.ts
- spx-gui/src/components/editor/code-editor/compiler.ts
- spx-gui/src/components/editor/code-editor/coordinators/index.ts
- spx-gui/src/components/editor/code-editor/ui/common/index.ts
- spx-gui/src/components/editor/code-editor/ui/features/completion-menu/completion-item-cache.ts
- spx-gui/src/components/editor/code-editor/ui/features/completion-menu/completion-menu.ts
this pr is about refactor completion menu cache
> refactor(spx-gui): refactor completion menu cache

- spx-gui/src/components/project/ProjectSharingLinkModal.vue
- spx-gui/src/components/project/index.ts
- spx-gui/src/components/project/runner/RunnerContainer.vue
- spx-gui/src/components/top-nav/TopNav.vue
- spx-gui/src/components/ui/UITextInput.vue
- spx-gui/src/components/ui/dialog/UIDialog.vue
- spx-gui/src/components/ui/modal/UIFormModal.vue
- spx-gui/src/components/ui/modal/UIModal.vue
> refactor: improve project sharing UX

- spx-gui/src/components/asset/animation/skeleton/SkeletonAnimationPlayer.vue
- spx-gui/src/components/asset/animation/skeleton/SkeletonAnimationRenderer.vue
- spx-gui/src/components/asset/animation/skeleton/shader.vert
- spx-gui/src/components/asset/library/details/SpriteCarousel.vue
- spx-gui/src/models/skeletonAnimation.ts
- update scale prop over related components to [number, number] type to match the scale property from animation avatar
- update the shader to scale the animation based on the scale property from animation avatar
- load and apply the scale property from animation avatar to the animation renderer
> fix: load scale property from avatar to auto scale the animation

- spx-gui/src/components/asset/library/AssetLibrary.vue
- spx-gui/src/components/asset/library/ai/AIBackdropEditor.vue
- spx-gui/src/components/asset/library/ai/AIPreviewModal.vue
- spx-gui/src/components/asset/library/ai/ImageEditor/ImageCrop.vue
- get project stage aspect ratio from project
- set default edit mode to 'crop' when selecting backdrop image
- set crop handlers to project stage aspect ratio and center the crop box
> feat: crop ai backdrop image to project stage aspect ratio by default

- spx-backend/cmd/spx-backend/gop_autogen.go
- spx-backend/cmd/spx-backend/post_aigc_inpainting.yap
- spx-backend/internal/controller/aigc.go
- spx-gui/src/apis/aigc.ts
- spx-gui/src/apis/asset.ts
- spx-gui/src/apis/util.ts
- spx-gui/src/components/asset/library/ai/AIBackdropEditor.vue
- spx-gui/src/components/asset/library/ai/AIPreviewModal.vue
- spx-gui/src/components/asset/library/ai/AISpriteEditor.vue
- spx-gui/src/components/asset/library/ai/ImageEditor/BrushSize.vue
- spx-gui/src/components/asset/library/ai/ImageEditor/ImageRepaint.vue
- spx-gui/src/components/asset/library/ai/ImageEditor/useUndoRedo.test.ts
- spx-gui/src/components/asset/library/ai/ImageEditor/useUndoRedo.ts
- spx-gui/src/components/ui/global.scss
- spx-gui/src/components/ui/icons/erase.svg
- spx-gui/src/models/aigc.ts
This pull request implements the inpainting feature for AI-generated previews.
Changes:
https://github.com/user-attachments/assets/72cd2bd8-08e4-4b74-b4e2-e16eb257012e
> Inpainting AI-generated previews

- spx-gui/src/components/asset/library/AssetLibrary.vue
- spx-gui/src/components/asset/library/LibraryTree.vue
- spx-gui/src/components/asset/library/category.ts
- Update the way to match the correct category presets.
- Let the tree select component to be reactive to current asset type.
- Now the backdrop and sound asset library could show the correct category select presets.
> fix: update correct category select presets for backdrop and sound asset

- tools/compiler/internal/base.go
- tools/compiler/internal/completion.go
- tools/compiler/internal/definition.go
- tools/compiler/internal/diagnostics.go
- tools/compiler/js.go
- tools/compiler/main.go
- tools/compiler/static/parent.html
fix: fix the bug of can't use the completion items in the end empty lines of file.
fix: fix get token details parameter names.
fix: split the baseToken struct from definition item struct.
fix: extract function `extractMethodsFromNamed`.
> fix`WASM Compiler`: fix some details.

- spx-backend/cmd/spx-backend/gop_autogen.go
> chore(spx-backend): regenerate `gop_autogen.go`

- tools/compiler/internal/base.go
- tools/compiler/internal/completion.go
- tools/compiler/internal/definition.go
- tools/compiler/static/parent.html
- fix: fix can't get the definition of var block.
- fix: fix the bug of hover out nothing.
- fix: change the way of get completion items.
- feat: add a filter to make sure only return current file's info(diagnostics, inlay hint, definitions).
> fix`WASM Compiler`: fix some bugs.

- tools/compiler/internal/ast.go
- tools/compiler/internal/base.go
- tools/compiler/internal/completion.go
> feat`WASM Compiler`: get struct field & method into completion item.

- spx-gui/src/utils/ispxLoader.ts
- tools/ispx/main.go
Removed JSON serialization and deserialization for ispx Wasm and JS communication
to improve performance and consistency with other interfaces
> refactor: Removed JSON serialization for ispx wasm-js communication

- spx-gui/src/components/editor/code-editor/EditorUI.ts
- spx-gui/src/components/editor/code-editor/coordinators/hoverProvider.ts
- spx-gui/src/components/editor/code-editor/coordinators/index.ts
- spx-gui/src/components/editor/code-editor/tokens/gop.ts
- spx-gui/src/components/editor/code-editor/tokens/spx.ts
- spx-gui/src/components/editor/code-editor/tokens/types.ts
- spx-gui/src/components/editor/code-editor/ui/EditorSidebar.vue
- spx-gui/src/components/editor/code-editor/ui/ToolItem.vue
- spx-gui/src/components/editor/code-editor/ui/common/index.ts
- spx-gui/src/components/editor/code-editor/ui/features/hover-preview/DocumentPreview.vue
this pr is about:
- add sidebar collapse animation.
- flat all categories, click nav tab or scoll will both sync category title position or nav active idx. 
- inputAssistant will filter inputAssistantItems for different code page.
> refactor(spx): inputAssistant Provider will filter Token effect in different  code page

- tools/compiler/internal/base.go
- tools/compiler/internal/completion.go
fix: rename `getScopesItems` -> `getCompletionItems`.
fix: fix wrong if statement.
> fix`WASM Compiler`: fix from #913 comment.

- spx-gui/src/components/editor/code-editor/chat-bot.ts
- spx-gui/src/components/editor/code-editor/compiler.ts
- spx-gui/src/components/editor/code-editor/coordinators/hoverProvider.ts
- spx-gui/src/components/editor/code-editor/coordinators/index.ts
- spx-gui/src/components/editor/code-editor/tokens/spx.ts
- spx-gui/src/components/editor/code-editor/ui/EditorSidebar.vue
- spx-gui/src/components/editor/code-editor/ui/MarkdownPreview.vue
- spx-gui/src/components/editor/code-editor/ui/features/completion-menu/CompletionMenuComponent.vue
- spx-gui/src/components/editor/code-editor/ui/features/completion-menu/completion-menu.ts
- spx-gui/src/components/editor/code-editor/ui/features/hover-preview/DocumentPreview.vue
this pr is about fix some new bugs
- Fix the issue with Markdown text being incorrectly displayed or garbled in the chat-bot dialog activated from inputAssistant.
- Resolve the problem where the completion menu does not correctly display documentation and fails to respond to click events in the actions area.
- Fix the issue where clicking the nav icon after displaying detailed documentation does not respond quickly and does not scroll to the correct position.
- Address the problem where focus does not fully return to the Monaco editor after clicking on linked elements in the completion menu.
- Adjust the margin issue between the first element of the Markdown Preview component and the Markdown display container.
> fix(spx-gui): fix new exits bugs

- tools/compiler/internal/ast.go
- tools/compiler/internal/base.go
- tools/compiler/internal/definition.go
- tools/compiler/internal/setups.go
Add comment into AST, usage in definition can get function comment as document.
> feat`WASM Compiler`: add comment into AST, usage in definition can get document.

- spx-gui/package-lock.json
- spx-gui/package.json
Fix vercel build error when configured with `NODE_ENV=production`
```
[16:04:32.020] > spx-gui@0.0.0 build
[16:04:32.020] > vue-tsc --build --force && vite build --mode ${NODE_ENV:-production}
[16:04:32.020] 
[16:04:32.025] sh: line 1: vue-tsc: command not found
[16:04:32.035] Error: Command "export PATH=$PATH:/usr/local/go/bin && sh build-wasm.sh && npm run build" exited with 127
```
Distingushment between `dependencies` & `devDependencies` is meant for server development with Node.js, while makes no sense for frontend application.
We can consider build tools for frontend application as `dependencies` instead of `devDependencies`, as the latter will not be installed when running `npm install` with `NODE_ENV=production`:
> With the `--production` flag (or when the `NODE_ENV` environment …
> Fix vercel build

- .github/workflows/publish-docker-image.yml
- scripts/k8s/redeploy/Dockerfile
- Change Docker image tag to `dev` for clarity regarding its use in testing environments.
- Remove obsolete `scripts/k8s/redeploy/Dockerfile`.
> chore(ci): change Docker image tag from `latest` to `dev`

- spx-gui/src/models/common/file.ts
- spx-gui/src/utils/file.ts
- Prevent setting of stale URLs in fast-switching scenarios.
- Fix security error in Firefox where old blob URLs were being accessed after navigation (e.g., when opening a new project while another is being edited).
---
For example, when switching from `http://localhost:5173/editor/test1` to `http://localhost:5173/editor/test2`:
P.S.: These errors are triggered by the use of `useFileUrl` in `StageViewer`.
> fix(utils/file): resolve race condition in `useFileUrl`

- spx-gui/src/components/editor/preview/stage-viewer/NodeTransformer.vue
- spx-gui/src/components/editor/preview/stage-viewer/StageViewer.vue
- spx-gui/src/models/project/index.ts
- spx-gui/src/utils/utils.ts
> Thumbnail generation for community

- spx-gui/src/models/project/index.test.ts
Tests show that `vi.runOnlyPendingTimersAsync` triggers timers but doesn't await async resolutions like `vi.advanceTimersToNextTimerAsync`, despite Vitest's documentation not specifying this.
---
For https://github.com/goplus/builder/actions/runs/11090293364/job/30812452094.
> test(models/project): flush promises after `vi.runOnlyPendingTimersAsync`

- spx-backend/.env.dev
- Use `utf8mb4` instead of `utf8` for full Unicode support. (Fixes #987)
- Set `loc` to `UTC` for consistent time zone handling.
---
TODO (after merge):
> chore(spx-backend): fix `GOP_SPX_DSN` in `.env.dev`

- spx-backend/internal/controller/user.go
- spx-backend/internal/controller/user_test.go
- spx-gui/src/components/community/user/FollowButton.vue
- spx-gui/src/components/navbar/NavbarProfile.vue
- spx-gui/src/components/project/ProjectCreateModal.vue
- spx-gui/src/pages/community/home.vue
- spx-gui/src/pages/editor/index.vue
- spx-gui/src/stores/user.ts
- Remove handling of refresh token expiration as Casdoor never returns `refresh_expires_in`[^1].
- Treat refresh tokens as always valid as they are renewed with each access token refresh[^2].
- Return `401 Unauthorized` instead of `500 Internal Server Error` when JWT parsing fails.
[^1]: https://github.com/casdoor/casdoor/blob/6f1f93725e77c8288aa0ac1c0d996feff906ddcf/object/token_oauth.go#L383-L390
[^2]: https://github.com/casdoor/casdoor/blob/6f1f93725e77c8288aa0ac1c0d996feff906ddcf/object/token_oauth.go#L351-L376
> refactor(auth): remove refresh token expiration handling

- spx-gui/src/components/community/user/FollowButton.vue
- spx-gui/src/components/navbar/NavbarNewProjectItem.vue
- spx-gui/src/components/navbar/NavbarOpenProjectItem.vue
- spx-gui/src/components/navbar/NavbarProfile.vue
- spx-gui/src/pages/community/explore.vue
- spx-gui/src/pages/community/user/projects.vue
- spx-gui/src/pages/editor/index.vue
- spx-gui/src/router.ts
- spx-gui/src/stores/user.ts
- spx-gui/src/utils/user.ts
- Add `useEnsureSignedIn` to prompt users to sign in before executing protected actions.
- Add similar protection for specific routes using navigation guards.
Fixes #974
> feat(auth): introduce sign-in guard

- docs/openapi.yaml
- spx-backend/cmd/spx-backend/get_assets_list.yap
- spx-backend/cmd/spx-backend/get_project-releases_list.yap
- spx-backend/cmd/spx-backend/get_projects_list.yap
- spx-backend/cmd/spx-backend/get_users_list.yap
- spx-backend/cmd/spx-backend/gop_autogen.go
- spx-backend/internal/controller/asset.go
- spx-backend/internal/controller/asset_test.go
- spx-backend/internal/controller/project.go
- spx-backend/internal/controller/project_release.go
- spx-backend/internal/controller/project_test.go
- spx-backend/internal/controller/user.go
- spx-backend/internal/controller/user_test.go
- spx-gui/src/apis/project.ts
- spx-gui/src/pages/community/user/followers.vue
- spx-gui/src/pages/community/user/following.vue
- spx-gui/src/pages/community/user/likes.vue
- spx-gui/src/pages/community/user/overview.vue
> feat: add `likedAt` order support in project listing API

- spx-gui/src/apis/project.ts
- spx-gui/src/components/community/CommunityNavbar.vue
- spx-gui/src/components/community/project/OwnerInfo.vue
- spx-gui/src/components/community/project/RemixedFrom.vue
- spx-gui/src/i18n.ts
- spx-gui/src/main.ts
- spx-gui/src/models/project/index.ts
- spx-gui/src/pages/community/explore.vue
- spx-gui/src/pages/community/home.vue
- spx-gui/src/pages/community/project.vue
- spx-gui/src/pages/community/search.vue
- spx-gui/src/pages/community/user/followers.vue
- spx-gui/src/pages/community/user/following.vue
- spx-gui/src/pages/community/user/likes.vue
- spx-gui/src/pages/community/user/overview.vue
- spx-gui/src/pages/community/user/projects.vue
- spx-gui/src/pages/editor/index.vue
- spx-gui/src/router.ts
- spx-gui/src/utils/route.ts
- spx-gui/src/utils/utils.ts
* Close #1008 
* Clear search input when leaving search page, close #1010 
* Use `displayName` instead of `name` for user displaying
* Adjust display order of like-count & view-count in project page
> Pages' title

- spx-gui/src/apis/project-release.ts
- spx-gui/src/apis/project.ts
- spx-gui/src/models/common/cloud.ts
- spx-gui/src/models/project/index.ts
- spx-gui/src/pages/community/project.vue
update #1033. Fix:
> 1. Prefer released game content (& thumbnail) in project page
> Fix project page game content

- spx-gui/src/components/community/project/ReleaseHistory.vue
- spx-gui/src/pages/community/project.vue
* Reset `ProjectRunner` when project changed
* Disable remixing for project with no releases, which causes 404 error
Legacy projects may be public while with no releases.
> Fix details for project page

- docs/openapi.yaml
- spx-backend/internal/controller/asset_test.go
- spx-backend/internal/controller/project.go
- spx-backend/internal/controller/project_release.go
- spx-backend/internal/controller/project_release_test.go
- spx-backend/internal/controller/project_test.go
- spx-backend/internal/controller/user_test.go
- spx-backend/internal/model/project.go
- spx-gui/src/apis/project-release.ts
- spx-gui/src/apis/project.ts
- spx-gui/src/models/common/cloud.ts
- spx-gui/src/models/project/index.ts
- spx-gui/src/pages/community/project.vue
- spx-gui/src/pages/docs/api.vue
- spx-gui/src/router.ts
> feat: add `Project.latestRelease` to track latest release

- spx-gui/.eslintrc.cjs
- spx-gui/src/components/project/ProjectPublishedModal.vue
- spx-gui/src/pages/community/search.vue
- spx-gui/src/utils/i18n/README.md
- spx-gui/src/utils/i18n/index.ts
- spx-gui/src/utils/utils.ts
Provide `I18nT` to simplify element translation:
```vue
<template>
<I18nT>
<template #en>Please <a :href="link">sign in</a>.</template>
<template #zh>请<a :href="link">登录</a>。</template>
</I18nT>
</template>
```
> Provide `I18nT` to simplify element translation

- spx-gui/src/components/project/ProjectItem.vue
- spx-gui/src/models/common/cloud.ts
- spx-gui/src/models/project/index.ts
- spx-gui/src/widgets/spx-runner/SpxRunner.ce.vue
When showcasing a project, such as in the `ProjectItem` component or project page, prefer published content rather than draft content. 
"Prefer published content" means to use the published content if it exists. 
"Published content exists" means the project is public and has a latest release, which is the "published content".
> Adjust preference for published content of project

- spx-gui/src/components/editor/preview/EditorPreview.vue
- spx-gui/src/components/project/runner/IframeDisplay.vue
- spx-gui/src/components/project/runner/ProjectRunner.vue
- spx-gui/src/components/project/runner/RunnerContainer.vue
- spx-gui/src/pages/community/project.vue
- spx-gui/src/widgets/spx-runner/SpxRunner.ce.vue
Preload resources (wasm & wasm_exec.js) for project runner to accelerate running project.
> Preload project runner

- spx-gui/src/components/community/user/UserItem.vue
Avoid empty description block in `UserItem`.
> Optimize style detail for `UserItem` with empty `description`

- spx-gui/src/models/project/index.test.ts
> test(models/project): precisely forward fake timers via `vi.advanceTimersByTime`

- spx-gui/src/components/editor/sprite/animation/AnimationPlayer.vue
`image.decode()` can sometimes fail even when the image can be  displayed correctly, resulting in the error:
```
EncodingError: The source image cannot be decoded.
```
Files that may trigger this issue can be found here: [decode_error_images.zip](https://github.com/user-attachments/files/17760016/decode_error_images.zip).
This problem may be linked to large image sizes. For further discussion, see: https://github.com/vuetifyjs/vuetify/issues/5418#issuecomment-489295740. However, this seems contradictory since `image.decode()` is intended to preload large images, as noted here: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/decode#usage_notes.
We will need to investigate this further.
> Ignore decode error of animation frames

- spx-gui/src/components/navbar/NavbarProfile.vue
- spx-gui/src/components/project/runner/ProjectRunner.vue
- spx-gui/src/utils/utils.test.ts
- spx-gui/src/utils/utils.ts
> UI for SPX version selector

- scripts/nginx.conf
Supplement to #1110.
> * Configure response headers (see details in [SPX 2.0 Integration #1083](https://github.com/goplus/builder/pull/1083)) for document requests of staging env
The `Cross-Origin-*` headers are also required for worker scripts (which are treated as "frame"s as well):
> Add `Cross-Origin-*` headers for worker script

- spx-gui/src/components/editor/sprite/animation/AnimationPlayer.vue
- spx-gui/src/utils/disposable.ts
Fix `this`-loss issue of `dispose` introduced in #1094.
Related discussion: https://github.com/goplus/builder/pull/1094#discussion_r1853634894
> Fix disposer issue

- tools/spxls/README.md
- tools/spxls/internal/importer.go
- tools/spxls/internal/server/command.go
- tools/spxls/internal/server/compile.go
- tools/spxls/internal/server/def.go
- tools/spxls/internal/server/document.go
- tools/spxls/internal/server/highlight.go
- tools/spxls/internal/server/highlight_test.go
- tools/spxls/internal/server/rename.go
- tools/spxls/internal/server/rename_test.go
- tools/spxls/internal/server/server.go
- tools/spxls/internal/server/signature.go
- tools/spxls/internal/server/signature_test.go
- tools/spxls/internal/server/util.go
- tools/spxls/internal/vfs/mapfs.go
- tools/spxls/main.go
> feat(tools/spxls): implement `textDocument/{prepareRename,rename,signatureHelp,documentHighlight}`

- tools/spxls/internal/server/compile.go
- tools/spxls/internal/server/highlight.go
- tools/spxls/internal/server/highlight_test.go
- tools/spxls/internal/server/semantic_token.go
- tools/spxls/internal/server/semantic_token_test.go
- tools/spxls/internal/server/server.go
- tools/spxls/internal/util/enclosing.go
> feat(tools/spxls): implement `textDocument/{semanticTokens/full,documentHighlight}`

- spx-gui/src/models/animation.test.ts
- spx-gui/src/models/animation.ts
- spx-gui/src/models/backdrop.ts
- spx-gui/src/models/common/asset.ts
- spx-gui/src/models/costume.ts
- spx-gui/src/models/project/index.ts
- spx-gui/src/models/sound.ts
- spx-gui/src/models/sprite.test.ts
- spx-gui/src/models/sprite.ts
There may be assets with field `builder_id` in asset-library, which are added by Spritehub rather than Builder.
Now we do control `includeID: bool` during both export and load processes, allowing us to exclude `builder_id` when adding asset from asset-library, to avoid issues caused by duplicate ID.
> Fix adding-asset from asset-library

- tools/spxls/README.md
- tools/spxls/internal/pkgdata/pkgdata.go
- tools/spxls/internal/server/command.go
- tools/spxls/internal/server/command_test.go
- tools/spxls/internal/server/compile.go
- tools/spxls/internal/server/completion.go
- tools/spxls/internal/server/completion_test.go
- tools/spxls/internal/server/diagnostic_test.go
- tools/spxls/internal/server/document_test.go
- tools/spxls/internal/server/server.go
- tools/spxls/internal/server/spx_definition.go
- tools/spxls/internal/server/util.go
> feat(tools/spxls): implement `textDocument/completion`

- spx-gui/src/components/editor/code-editor/code-editor.ts
- spx-gui/src/components/editor/code-editor/common.ts
- spx-gui/src/components/editor/code-editor/lsp/index.ts
- spx-gui/src/components/editor/code-editor/lsp/spxls/methods.ts
- spx-gui/src/components/editor/code-editor/ui/resource-reference/index.ts
Use definition from `textDocument/documentLink` for
* Hover action, close #1105 
* ContextMenu item
> Use definition from `textDocument/documentLink`

- spx-gui/src/components/editor/code-editor/code-editor.ts
- spx-gui/src/components/editor/code-editor/common.ts
- spx-gui/src/components/editor/code-editor/document-base/spx.ts
- spx-gui/src/components/editor/code-editor/lsp/index.ts
- spx-gui/src/components/editor/code-editor/lsp/spxls/methods.ts
- spx-gui/src/components/editor/code-editor/ui/code-editor-ui.ts
- spx-gui/src/components/editor/code-editor/ui/completion/CompletionCard.vue
- spx-gui/src/components/editor/code-editor/ui/completion/CompletionItem.vue
- spx-gui/src/components/editor/code-editor/ui/completion/index.ts
- spx-gui/src/utils/spx/index.ts
- tools/spxls/internal/server/protocol.go
- tools/spxls/internal/server/spx_definition.go
> LS integration for Completion

- spx-gui/src/components/editor/preview/stage-viewer/SpriteNode.vue
- spx-gui/src/models/common/file.ts
- spx-gui/src/models/costume.ts
Updated behavior: Use the `viewBox` size for SVG images in Builder to ensure consistency with SPX.
Previous behavior: We retrieved the size of the `<img>` element containing SVG to determine the image size. While it was rendered within a `300x150` box by default, resulting in dimensions like `300x150`, `140x150`, `300x100`, etc.
> Why is the rendered SVG sometimes very small?
> 
> In some user-agents, when they fail to calculate a size for the element they fall back to a default size for replaced elements of 300px width × 150px height. That size is from deep within [a dark corner of the CSS 2.1 spec](http://www.w3.org/TR/CSS2/visudet.html#inline-replaced-width), so I guess that’s somewhat reasonable. Mostly it seems to happen when the viewBox attribute values are set in pixels instead of …
> Fix image size for svg

- spx-gui/src/models/common/file.ts
In follow-up to #1186.
spx uses value of attribute `width` & `height` when attribute `viewBox` lacks a valid value. Details can be found at https://github.com/qiniu/oksvg/blob/917f53935572252ba3da8909ca4fbedec418bde1/svgd.go#L1015-L1049
We are replicating this logic for consistency.
> Fix SVG size retrieval logic

- spx-backend/internal/copilot/custom_element_code_change.md
- spx-gui/src/components/common/markdown-vue/MarkdownView.ts
- spx-gui/src/components/editor/code-editor/ui/markdown/CodeChange.vue
- spx-gui/src/components/editor/code-editor/ui/markdown/CodeView.vue
- spx-gui/src/components/editor/code-editor/ui/markdown/MarkdownView.vue
* Fix `code-change` in markdown to allow blank lines, closes #1184
* Additional updates:
- Optimize style for the "invalid" placeholder in `CodeChange`
- Fix visibility of line numbers in `CodeView`
Blank lines may appear in the content of the `code-change` component, such as:
```html
<code-change file="...">
var a int
onStart => {
// ...
}
</code-change>
```
While according to Markdown specifications (e.g., [CommonMark](https://spec.commonmark.org/0.31.2/#html-blocks)), blank lines are not permitted within HTML blocks, except for tags like `pre`, `script`, `style`, and `textarea`. As a result, `MarkdownView` does not parse the above example corretly.
To allow blank lines in content of custom elements, we introduced the `is` attribute, allowing them to be declared as a `pre` element. The …
> Fix code-change in markdown with blank-line content

- spx-gui/src/components/editor/code-editor/CodeLink.vue
- spx-gui/src/components/editor/code-editor/context.ts
- spx-gui/src/components/editor/code-editor/ui/CodeEditorUI.vue
- spx-gui/src/components/editor/code-editor/ui/MonacoEditor.vue
- spx-gui/src/components/editor/code-editor/ui/api-reference/APIReferenceItem.vue
- spx-gui/src/components/editor/code-editor/ui/api-reference/APIReferenceUI.vue
- spx-gui/src/components/editor/code-editor/ui/api-reference/index.ts
- spx-gui/src/components/editor/code-editor/ui/code-editor-ui.ts
- spx-gui/src/components/editor/code-editor/ui/completion/CompletionUI.vue
- spx-gui/src/components/editor/code-editor/ui/completion/index.ts
- spx-gui/src/components/editor/code-editor/ui/context-menu/ContextMenu.vue
- spx-gui/src/components/editor/code-editor/ui/context-menu/ContextMenuUI.vue
- spx-gui/src/components/editor/code-editor/ui/context-menu/index.ts
- spx-gui/src/components/editor/code-editor/ui/diagnostics/index.ts
- spx-gui/src/components/editor/code-editor/ui/hover/HoverCard.vue
- spx-gui/src/components/editor/code-editor/ui/hover/HoverUI.vue
- spx-gui/src/components/editor/code-editor/ui/hover/index.ts
- spx-gui/src/components/editor/code-editor/ui/resource-reference/index.ts
- spx-gui/src/components/editor/code-editor/ui/resource-reference/selector/ResourceSelector.vue
- spx-gui/src/pages/editor/index.vue
- spx-gui/src/utils/disposable.ts
- spx-gui/src/utils/exception.ts
- spx-gui/src/utils/query.ts
- spx-gui/src/utils/task.ts
- spx-gui/src/utils/utils.ts
- tools/spxls/client.ts
* Exception handling in code editor, close #1134
* Debug project-switching in editor
> Exception handling in code editor

- spx-gui/build-wasm.bat
- spx-gui/build-wasm.sh
The `wasm_exec.js` file is already tracked at `spx-gui/src/assets/wasm_exec.js`, making the copy step redundant.
Additionally, copying from `$GOROOT/misc/wasm/wasm_exec.js` is unreliable because:
1. In Go 1.24, the file will be moved to `$GOROOT/lib/wasm`[^1].
2. `$GOROOT/misc` is not included in Go toolchain archives, which breaks Wasm builds when using `GOTOOLCHAIN`[^2].
[^1]: https://tip.golang.org/doc/go1.24#wasm
[^2]: https://go.dev/issue/68024
> chore: remove `wasm_exec.js` copy step from Wasm build scripts

- spx-gui/src/components/asset/library/AssetAddModal.vue
- spx-gui/src/components/asset/library/AssetLibraryModal.vue
- spx-gui/src/components/asset/library/category.ts
Updates https://github.com/goplus/builder/issues/1062#issuecomment-2574867274
> Update categories for asset backdrop & sound

- spx-gui/src/components/editor/code-editor/ui/code-editor-ui.ts
- tools/spxls/internal/server/protocol.go
- tools/spxls/internal/server/spx_definition.go
- tools/spxls/internal/server/util.go
> Fix go-to-definition within same document

- spx-gui/src/components/project/runner/v1/ProjectRunnerV1.vue
- spx-gui/src/components/project/runner/v2/ProjectRunnerV2.vue
- spx-gui/src/models/common/file.ts
- spx-gui/src/utils/img.ts
When running project with spx v1, we convert svg files to png before sending them to spx, for
1. Compatibility: Many SVG features are not supported in spx v1
2. Improve performance: SVG rendering is slow in spx v1, close #1208.
> Improve compatibility & performance for svg in spx v1

- spx-gui/src/components/editor/code-editor/ui/diagnostics/index.ts
- spx-gui/src/components/editor/code-editor/ui/resource-reference/index.ts
> Refresh LS result on project change

- spx-gui/src/components/editor/preview/EditorPreview.vue
- spx-gui/src/components/project/runner/ProjectRunner.vue
- spx-gui/src/components/project/runner/v1/ProjectRunnerV1.vue
- spx-gui/src/components/project/runner/v2/ProjectRunnerV2.vue
- spx-gui/src/utils/img.ts
In #1229, we convert SVG images to PNG before project execution, resulting in slower "running". In this PR, we:
* Use `OffscreenCanvas` instead of `Canvas`
* Implement caching for converted results
to mitigate this issue.
> Optimize speed for running project

- spx-gui/src/components/editor/code-editor/document-base/spx/index.ts
* Document definitions for spx `MovingInfo` & `TurningInfo`, close #1237
* Fix `Sprite.turnTo#3`
> Document definitions for spx MovingInfo & TurningInfo

- spx-gui/src/components/editor/code-editor/document-base/gop.ts
- tools/spxls/internal/server/compile.go
- tools/spxls/internal/server/completion.go
- tools/spxls/internal/server/completion_test.go
- tools/spxls/internal/server/spx_definition.go
- tools/spxls/internal/server/util.go
Updates #1199:
- https://github.com/goplus/builder/issues/1199#issuecomment-2574226700
- https://github.com/goplus/builder/issues/1199#issuecomment-2579301987
> refactor(tools/spxls): improve completion support

- tools/spxls/internal/server/command.go
- tools/spxls/internal/server/command_test.go
- tools/spxls/internal/server/compile.go
- tools/spxls/internal/server/completion.go
- tools/spxls/internal/server/definition.go
- tools/spxls/internal/server/diagnostic_test.go
- tools/spxls/internal/server/document.go
- tools/spxls/internal/server/document_test.go
- tools/spxls/internal/server/format.go
- tools/spxls/internal/server/format_test.go
- tools/spxls/internal/server/highlight.go
- tools/spxls/internal/server/hover.go
- tools/spxls/internal/server/implementation.go
- tools/spxls/internal/server/reference.go
- tools/spxls/internal/server/rename.go
- tools/spxls/internal/server/semantic_token.go
- tools/spxls/internal/server/signature.go
- tools/spxls/internal/server/spx_definition.go
- tools/spxls/internal/server/util.go
Currently, errors returned by `Server.compile` are only fatal errors that make the compilation result completely unusable. Therefore, we no longer ignore these errors in most cases.
> refactor(tools/spxls): improve compile error handling and add spx type getters

- spx-gui/src/components/editor/preview/InPlaceRunner.vue
> fix(InPlaceRunner): filter out igop Wasm PATH error in console output

- spx-gui/src/components/editor/code-editor/ui/markdown/CodeView.vue
- tools/spxls/internal/server/compile.go
- tools/spxls/internal/server/definition.go
- tools/spxls/internal/server/document.go
- tools/spxls/internal/server/highlight.go
- tools/spxls/internal/server/hover.go
- tools/spxls/internal/server/implementation.go
- tools/spxls/internal/server/protocol.go
- tools/spxls/internal/server/reference.go
- tools/spxls/internal/server/rename.go
- tools/spxls/internal/server/server.go
* Related project: https://github.com/orgs/goplus/projects/6/views/1
> Release v1.6.1

- spx-gui/src/pages/sign-in/callback.vue
- spx-gui/src/pages/sign-in/token.vue
- spx-gui/src/router.ts
- spx-gui/src/stores/user/signed-in.ts
close #1279.
> We allow asset-makers to sign into Builder as Curator, enabling them to review private assets before the assets get published and available to all Builder users.
For asset-makers, sign into Builder as Curator by:
1. Open `https://<host>/sign-in/token`. For env production, it's https://builder.goplus.org/sign-in/token
2. Paste (access) token for "Curator", then submit
3. Now signed in as "Curator"
> Page `/sign-in/token`

- spx-backend/internal/copilot/spx_defs.md
- spx-gui/src/components/editor/code-editor/document-base/spx/index.ts
> Fix doc for `setHeading`

- spx-gui/src/components/editor/panels/stage/StagePanel.vue
- spx-gui/src/models/stage.ts
* Fix auto-selection for widgets
* Fix border-radius for stage panel
> Fix widget details

- spx-gui/src/components/editor/code-editor/ui/code-editor-ui.ts
- spx-gui/src/components/editor/code-editor/ui/resource-reference/index.ts
> Fix text-document tab related issues

- tools/spxls/internal/server/compile.go
- tools/spxls/internal/server/format.go
- tools/spxls/internal/server/format_test.go
- tools/spxls/internal/vfs/mapfs.go
- tools/spxls/internal/vfs/mapfs_test.go
> fix(tools/spxls): preserve doc comments after formatting

- tools/spxls/internal/server/format.go
- tools/spxls/internal/server/format_test.go
- Fixed declaration end position handling to account for trailing comments.
- Ensured correct trailing newlines after declarations and comments.
- Fixed the exclusion of non-floating comments.
> fix(tools/spxls): improve declaration end position handling in formatting

- docs/develop/guidance/achieve_Tagging.md
- docs/develop/guidance/feature_Mask.md
- docs/develop/guidance/feature_Tagging.md
- docs/develop/guidance/module_Mask.md
- docs/develop/guidance/module_Tagging.md
以下修改来自于：https://github.com/goplus/builder/pull/1331#discussion_r1955476192
- Tagging
- 标注方
- 消费方
- 单例全局唯一
- Mask
```ts
type Props = {
visible: boolean; // 是否显示蒙层
tags: string[]; // 需要高亮组件的查找路径
};
```
考虑了 tag选择器 的形式查找元素，通过传入key数组找到目标组件。
> Add doc for Mask and Tagging

- tools/spxls/internal/server/compile.go
- tools/spxls/internal/server/hover_test.go
- tools/spxls/internal/server/util.go
> fix(tools/spxls): correct identification of builtin objects with empty package paths

- tools/spxls/internal/server/format.go
- tools/spxls/internal/server/format_test.go
> fix(tools/spxls): preserve floating comments following shadow entry declarations

- tools/spxls/internal/server/command_test.go
- tools/spxls/internal/util/enclosing.go
> fix(tools/spxls): remove nil nodes from children list in `util.PathEnclosingInterval`

- spx-gui/src/components/guidance/step/FollowingStep.vue
> fix: Repair the listener removing logic in FollowingStep

- spx-gui/src/components/guidance/step/FollowingStep.vue
> fix: Update bubble arrow direction and adjust bubble content styling

- spx-gui/src/components/guidance/step/FollowingStep.vue
因为之前没有对AssetLibrary这里的高亮引导UI做适配，导致引导UI会渲染到屏幕外面。
于是加了个大元素检测，如果与屏幕的宽比>0.8或者高比>0.7则使用不一样样式计算方式。并且为了处理气泡内文字可能会超出气泡，改用动态绑定来动态处理气泡内容的padding值。
> fix: Update bubble content styling and adjust positioning for large elements

- spx-gui/src/components/guidance/step/FollowingStep.vue
@nighca 寒星老师我这边做了一点修改，您看看
在rename-modal-form的步骤时，会发生要监听的元素获取不到的情况。但是我发现MaskWithHighLight是能正常获取的，所以问题出在FollowingStep里，具体原因如下：
1. 触发事件处理器
2. 事件处理器调用API创建模态框
3. Vue开始渲染模态框组件
4. 同时FollowingStep检测到步骤变化并尝试查找新元素
5. 此时模态框尚未渲染完成，因此查找失败
因此我加上了异步重试机制，使用 Promise.all 并行处理所有路径。
> fix: Improve event listener setup with element waiting logic

- spx-gui/src/components/common/MaskWithHighlight.vue
- spx-gui/src/utils/tagging/TagRoot.vue
- spx-gui/src/utils/tagging/TagSelector.vue
- spx-gui/src/utils/tagging/index.ts
1. tagApi添加`getAllTagElements`，返回`elementToNode`, `nodeToPath`的映射关系提供给`TagSelector`使用。
2. 添加一个新的`TagSelector`组件，用于可视化选择`path`，并支持将TagNode组件路径复制到剪贴板。
```ts
type props = {
active: boolean;    // 是否使用TagSelector
}
```
体验地址：https://minorcell.github.io/tagging-demo/
> Add TagSelector

- spx-backend/internal/controller/project.go
@nighca  
修复了“ProjectA”在用户“项目列表”中展示的错误。之前获取项目信息时没有返回hidden字段，导致在“StoryLine”引导过程中，自动更新会默认将hidden字段设置为0，从而覆盖了“ProjectA”原本的hidden值。
> Fix ProjectA bug

- spx-gui/src/apis/util.ts
> refactor(apis/util): work around CDN back-to-origin slowness in `makeObjectUrls`

- spx-gui/src/components/editor/code-editor/code-editor.ts
- spx-gui/src/components/editor/code-editor/common.ts
- spx-gui/src/components/editor/code-editor/lsp/spxls/commands.ts
* Replaced the `acceptType` property with a new `accept` property in `InputSlot`, which uses the newly introduced `InputSlotAccept` type to provide more detailed information about accepted input types
* Added a `ResourceContextURI` type to represent URIs for resource contexts
> Extend accept info for `InputSlot`

- spx-gui/src/components/editor/code-editor/ui/context-menu/ContextMenuTrigger.vue
- spx-gui/src/components/editor/code-editor/ui/context-menu/ContextMenuUI.vue
- spx-gui/src/components/editor/code-editor/ui/context-menu/index.ts
close #1376.
> 沟通后调整为把按钮往左移，移出代码编辑区，这样不会遮盖代码
> 
> 不往上方移是因为，那样的话，按钮跟被选中的文本既不在水平方向上对齐也不在垂直方向上对齐，很难建立 context menu 与被选中文本的联系
> Adjust position for ContextMenu trigger

- .github/workflows/validate.yml
- tools/ai/ai.go
- tools/ai/backoff.go
- tools/ai/backoff_test.go
- tools/ai/command.go
- tools/ai/command_test.go
- tools/ai/go.mod
- tools/ai/kb.go
- tools/ai/kb_test.go
- tools/ai/transport.go
- tools/ai/transport_test.go
> feat: add tools/ai

- tools/ai/wasmtrans/promise.go
- tools/ai/wasmtrans/wasmtrans.go
> feat: add tools/ai/wasmtrans

- spx-gui/.env
- spx-gui/install-spx.sh
- spx-gui/src/components/project/runner/v2/ProjectRunnerV2.vue
* Upgrade spx to v2.0.13, related release: https://github.com/goplus/godot/releases/tag/spx2.0.13
* Use `onGameError` to detect game failure, related: https://github.com/goplus/spx/pull/669
> Upgrade spx to v2.0.13

- spx-gui/.env.production
update #1742.
Related:
* https://github.com/goplus/casdoor/pull/11
* https://github.com/goplus/builder/issues/1734
> Use `acc.xbuilder.com` instead of `acc.goplus.org`

- spx-gui/src/components/community/user/EditProfileModal.vue
- spx-gui/src/components/community/user/UserHeader.vue
- spx-gui/src/components/editor/code-editor/ui/copilot/UserMessage.vue
- spx-gui/src/components/navbar/NavbarProfile.vue
```
GET https://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83eo3arn6GG9ibmYYlticQj02YgJ6xfIbQnIlL4SzdEd7al3wSwpKwtPwbianHHTdffsEPfOGTeZGJa9HQ/132 net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep 200 (OK)
```
Follow up for https://github.com/goplus/builder/pull/1741.
在 https://github.com/goplus/builder/pull/1741#discussion_r2113396615 我们提到
> 这个在后续的维护中不会是大的负担是因为，如果需要做特别处理而没有，那么在开发时就会立刻发现（COEP 会 block 对应的请求，即使是本地开发模式）
这个并不完全正确，即使代码没有做特殊处理，但如果外部 URL 对应的服务（如本地或测试环境 avatar 对应的 `avatars.githubusercontent.com`）返回了 `cross-origin-resource-policy: cross-origin`，那么问题并不会暴露，直到遇到这样的 URL：其对应的外部服务不返回该响应头，才会暴露问题
> Debug user avatar loading

- spx-gui/build-wasm.sh
The file `src/assets/wasm/wasm_exec.js` from `$(go env GOROOT)/lib/wasm/wasm_exec.js` is not writable by default.
```
(base) ➜  spx-gui git:(build-wasm-script) ll src/assets/wasm 
total 142968
-rwxr-xr-x  1 nighca  staff    53M Jun  9 11:50 ispx.wasm
-rw-r--r--  1 nighca  staff   9.7K Jun  9 11:50 spxls-pkgdata.zip
-rwxr-xr-x  1 nighca  staff    17M Jun  9 11:50 spxls.wasm
-r--r--r--  1 nighca  staff    17K Jun  9 11:50 wasm_exec.js
```
It causes error when trying to run `build-wasm.sh` if `src/assets/wasm/wasm_exec.js` already exists:
```
cp: src/assets/wasm/wasm_exec.js: Permission denied
```
Here we use `cp -f` to avoid the failure.
> Avoid permission denied for `cp` in `build-wasm.sh`

- docs/develop/in-editor-router/base.ts
- docs/develop/in-editor-router/impl_CodeEditorUI.ts
- docs/develop/in-editor-router/impl_EditorState.ts
- docs/develop/in-editor-router/impl_SpriteEditor.ts
- docs/develop/in-editor-router/impl_SpritesPanel.ts
- docs/develop/in-editor-router/index.md
- docs/develop/in-editor-router/module_AnimationsEditor.ts
- docs/develop/in-editor-router/module_BackdropsEditor.ts
- docs/develop/in-editor-router/module_CostumesEditor.ts
- docs/develop/in-editor-router/module_EditorState.ts
- docs/develop/in-editor-router/module_SpriteEditor.ts
- docs/develop/in-editor-router/module_StageEditor.ts
- docs/develop/in-editor-router/module_WidgetsEditor.ts
- docs/develop/in-editor-router/tsconfig.json
Udpate #1139.
Review at https://github.com/nighca/goplus-builder/blob/issue-1139/docs/develop/in-editor-router/index.md .
> Tech Design for In-editor Routing

- .github/workflows/release.yml
> Use branch `main` instead of `dev` for workflow release

- spx-backend/cmd/spx-backend/main.yap
- spx-backend/cmd/spx-backend/post_asset.yap
- spx-backend/cmd/spx-backend/post_copilot_message.yap
- spx-backend/cmd/spx-backend/post_copilot_stream_message.yap
- spx-backend/cmd/spx-backend/post_workflow_stream_message.yap
- spx-backend/cmd/spx-backend/put_asset_#id.yap
- spx-backend/cmd/spx-backend/xgo_autogen.go
- spx-backend/internal/authz/authz.go
- spx-backend/internal/authz/authz_test.go
- spx-backend/internal/authz/context.go
- spx-backend/internal/authz/context_test.go
- spx-backend/internal/authz/helper.go
- spx-backend/internal/authz/helper_test.go
- Add `authz.ConsumeQuota` helper that extracts user and authorizer from context, eliminating need to maintain authorizer instances.
- Inject authorizer instance into request context via middleware for seamless access.
- Remove `authz.Authorizer.ConsumeQuota` method in favor of simplified context-based approach.
- Rename `authz.UserCanManageAssets` to `authz.CanManageAssets` and `authz.UserCanUsePremiumLLM` to `authz.CanUsePremiumLLM` for consistent AuthZ API naming.
> feat(spx-backend): introduce context-based `authz.ConsumeQuota` helper func

- spx-gui/src/models/sound.ts
- spx-gui/src/models/sprite.ts
- spx-gui/src/models/stage.ts
Related: #1880.
To allow special spx features like `triggerLayer` / `collisionByShape` (by browser devtool).
For example, run
```ts
project.stage.setExtraConfig({ debug: true, collisionByShape: true })
```
to enabe debug-mode & shape-collision for specific project.
> Add `extraConfig` for Stage, Sprite & Sound

- spx-gui/package-lock.json
- spx-gui/src/components/common/markdown-vue/MarkdownView.test.ts
- spx-gui/src/components/common/markdown-vue/MarkdownView.ts
- spx-gui/src/components/copilot/CopilotRoot.vue
- spx-gui/src/components/copilot/CopilotUI.vue
- spx-gui/src/components/copilot/MarkdownView.vue
- spx-gui/src/components/copilot/copilot.ts
- spx-gui/src/components/copilot/custom-elements/CodeChange.vue
- spx-gui/src/components/copilot/custom-elements/CodeLink.ts
- spx-gui/src/components/copilot/custom-elements/HighlightLink.vue
- spx-gui/src/components/copilot/custom-elements/ToolUse.vue
- spx-gui/src/components/editor/code-editor/CodeLink.vue
- spx-gui/src/components/tutorials/TutorialCourseSuccess.vue
- spx-gui/src/components/tutorials/TutorialRoot.vue
close #1913.
> * Custom element with raw (including blank line) content
>   See details in [Fix code-change in markdown with blank-line content #1193](https://github.com/goplus/builder/pull/1193)
We introduce `components.customRaw`, which ensures given custom components rendered like ["HTML raw tag names"](https://github.com/micromark/micromark/blob/774a70c6bae6dd94486d3385dbd9a0f14550b709/packages/micromark-util-html-tag-name/readme.md#htmlrawnames). So `<pre is="...">` is not needed any more.
> * Ignore incomplete html tag content when streaming
We discard incomplete HTML tag content before rendering.
> * Support self-closing
Self-closing for custom components are always supported now.
> Better rendering for LLM generated markdown content

- spx-gui/src/components/navbar/NavbarWrapper.vue
We will add the entry back when https://github.com/goplus/builder/issues/1829 is ready.
> Remove entry for Tutorials from Navbar temporarily

- spx-gui/src/models/common/cloud.ts
Add 10 KB threshold to `isInlineable` function to prevent large text files from being stored as inline data URLs in database. Large files now use cloud storage instead, reducing database pressure and avoiding MySQL JSON field size limits.
Fixes #1922
> feat: add file size limit for inline files

- spx-gui/src/components/editor/code-editor/ui/MonacoEditor.vue
> fix: disable ambiguous character highlighting in `MonacoEditor`

- spx-gui/src/components/editor/sound/SoundEditor.vue
close #2031
We export edited sound files in `wav` format; therefore, the file extension must be updated accordingly.
> Fix sound file extension after editing

- spx-gui/src/components/copilot/CopilotInput.vue
- spx-gui/src/components/copilot/CopilotUI.vue
- Fix Copilot scrollbar overflowing the container in older versions of Safari
- keep Copilot output and input font-size consistent
Updates #2055
> feat(spx-gui): improve Copilot UI acceptance issues

- .github/dependabot.yml
Migrate from individual ecosystem updates to multi-ecosystem groups [^1][^2] to reduce PR volume and improve dependency management workflow:
- Add `infrastructure` group for GitHub Actions with weekly scheduling
- Add `go-modules` group consolidating `spx-backend`, `tools/spxls`, and `tools/ai`
- Use `directories` field to manage multiple Go module paths under single ecosystem
[^1]: https://github.blog/changelog/2025-07-01-single-pull-request-for-dependabot-multi-ecosystem-support/
[^2]: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/configuring-multi-ecosystem-updates
> chore: configure Dependabot multi-ecosystem groups for streamlined updates

- spx-backend/internal/controller/aidescription.go
- spx-backend/internal/controller/aidescription_test.go
- spx-gui/src/models/project/index.ts
Increase backend `maxContentLength` limit to 150k for AI Description and add sophisticated truncation logic in frontend to ensure content stays within budget constraints and avoid validation errors.
> feat: enforce AI Description payload budgets

- spx-gui/src/components/project/sharing/ProjectDirectShare.vue
- spx-gui/src/components/project/sharing/ProjectPoster.vue
- spx-gui/src/components/project/sharing/ProjectRecordingSharing.vue
- spx-gui/src/components/project/sharing/ProjectScreenshotSharing.vue
- spx-gui/src/components/project/sharing/platform-share.ts
- platform-share
- add `createManualShareGuideUI` function
- add `createBlobDownloadHandler` function
- add `createImageManualShareGuide` use `createManualShareGuideUI`,createBlobDownloadHandler` to generate component guide user to share image
- add `createVideoManualShareGuide` use `createManualShareGuideUI`,createBlobDownloadHandler` to generate component guide user to share video
- add `createJumpLinkComponent` satisfy the need of platform jump to share
- other
- according to platform-share new function change three share module's logic
> feat:add sharefunction supportedtips

- spx-gui/src/models/project/index.ts
- spx-gui/src/models/tilemap.test.ts
- spx-gui/src/models/tilemap.ts
> feat(spx-gui): add tilemap's layer zIndex property & dispose tilemap load the project

- spx-gui/src/components/editor/sprite/SpritePhysicsEditor.vue
> Disable `imageSmoothingEnabled` for `SpritePhysicsEditor`

- spx-gui/src/components/ui/form/UIFormItem.vue
> fix(spx-gui): fix input issue
