docs/Sprite List & Sprite Library.md

Create Sprite List & Sprite Library

Create Sprite List & Sprite Library

---

docs/CodeEditor.md
docs/FileManager.md

This documentation provides a detailed comparative analysis of three mainstream code editors: CodeMirror, Monaco Editor, and Ace Editor. After careful consideration, the final choice is Monaco Editor due to its rich feature set, excellent performance, and seamless integration with Visual Studio Code. The provided Vue 3 demo illustrates a simple implementation of Monaco Editor, showcasing its capabilities.
The FileManager documentation compares the File System API and a JavaScript Tree approach for managing files. After evaluating the pros and cons, the JavaScript Tree method is recommended for its flexibility and compatibility across different environments. The documentation includes a sample directory structure and a demo showcasing the organization of files for a hypothetical project.

Add: CodeEditor & FileManager docs

---

spx-gui/src/class/AssetBase.ts
spx-gui/src/class/FileWithUrl.ts
spx-gui/src/class/backdrop.ts
spx-gui/src/class/sound.ts
spx-gui/src/class/sprite.ts
spx-gui/src/components/spx-stage/SpxStage.vue
spx-gui/src/interface/file.ts
spx-gui/src/store/modules/backdrop/index.ts
spx-gui/src/store/modules/project/index.ts
spx-gui/src/util/global.ts

#44 Add Sprite costume, add basic `config` (to generate `index.json`) configuration, add setter and getter functions to make resource files more usable.

feat: add current Costume

---

spx-gui/src/components/sprite-list/SpriteEditBtn.vue

#35 Allows users to edit Sprite position, heading, size

feat(gui):Bind the current sprite configuration of filemanager to the sprite editor

---

spx-gui/README.md

Update README.md for Code Styles Section

---

docs/architecture/project-manage.md

docs: project manage architecture doc

---

spx-gui/src/components/stage-viewer-demo/StageViewerDemo.vue
spx-gui/src/components/stage-viewer/BackdropLayer.vue
spx-gui/src/components/stage-viewer/Costume.vue
spx-gui/src/components/stage-viewer/Sprite.vue
spx-gui/src/components/stage-viewer/SpriteLayer.vue
spx-gui/src/components/stage-viewer/StageViewer.ts
spx-gui/src/components/stage-viewer/StageViewer.vue
spx-gui/src/components/stage-viewer/index.ts
spx-gui/src/router/index.ts
spx-gui/src/view/HomeView.vue

#59 
Allows different sizes of the stage to be displayed on the stage-viewer, allows set the stage size directly or obtain the actual stage size from the background picture, and the spx sprite can render updates in different sizes normally

refract & enhance stage viewer

---

spx-gui/package-lock.json
spx-gui/package.json
spx-gui/public/js/filesystem.js
spx-gui/src/class/asset-base.ts
spx-gui/src/class/project.ts
spx-gui/src/components/spx-stage/SpxStage.vue
spx-gui/src/components/top-menu/TopMenu.vue
spx-gui/src/store/modules/project/index.ts
spx-gui/src/util/file-system.ts
spx-gui/src/util/file.ts
spx-gui/src/util/global.ts

fix: Modify the code according to the architecture

---

spx-gui/public/js/filesystem.js
spx-gui/src/class/project.ts
spx-gui/src/components/top-menu/TopMenu.vue
spx-gui/src/store/modules/project/index.ts
spx-gui/src/util/file-system.ts
spx-gui/src/util/file.ts

#44 This pr mainly solves zip and summary related problems, the external can asynchronously get the zip file of the project through `project.zip`.

fix: Improve the logic related to save local

---

spx-gui/src/api/asset.ts
spx-gui/src/components/sprite-list/AssetAddBtn.vue
spx-gui/src/components/spx-library/LibraryModal.vue
spx-gui/src/components/spx-library/SpriteCard.vue
spx-gui/src/language/index.ts

feat: multi costume upload, and first image display in list

---

.github/workflows/lint.yml
.github/workflows/main.yml
spx-gui/.env
spx-gui/.env.example
spx-gui/README.md
spx-gui/env.d.ts
spx-gui/src/axios/index.ts

Modified .env injection according to comments in #111. Add current public env to .env into the repo.
The CI should runs only when files in spx-gui change, but not on .md files changes.

add public .env and CI conditions

---

spx-gui/src/store/modules/user/index.ts

Refactored JWT payload types due to a request to access user ID.

add fields for user's jwt payload

---

docs/architecture/stage-viewer.md
spx-gui/.eslintrc.cjs
spx-gui/src/class/asset-base.ts
spx-gui/src/class/backdrop.ts
spx-gui/src/components/spx-stage/SpxStage.vue
spx-gui/src/components/stage-viewer-demo/StageViewerDemo.vue
spx-gui/src/components/stage-viewer/BackdropLayer.vue
spx-gui/src/components/stage-viewer/Costume.vue
spx-gui/src/components/stage-viewer/Sprite.vue
spx-gui/src/components/stage-viewer/SpriteLayer.vue
spx-gui/src/components/stage-viewer/StageViewer.vue
spx-gui/src/components/stage-viewer/common.ts
spx-gui/src/components/stage-viewer/index.ts
spx-gui/src/interface/file.ts

feat:support more spx config & refactor interface in stage viewer

---

spx-gui/src/class/project.ts
spx-gui/src/components/sprite-list/AssetAddBtn.vue
spx-gui/src/util/file.ts

As shown below, you can now add a background to run the project as the default entry code is implemented.

feat: generate default entrycode

---

spx-gui/src/api/project.ts
spx-gui/src/class/project.ts
spx-gui/src/components/top-menu/TopMenu.vue
spx-gui/src/interface/library.ts
spx-gui/src/store/modules/project/index.ts

feat: save cloud and get cloud projects

---

spx-gui/src/components/spx-stage/SpxStage.vue
spx-gui/src/components/stage-viewer/StageViewer.vue

#140 
A size listener is registered in spx-stage to listen for container size changes
Modified in component to replace the size obtained from dom directly by obtaining the container size from props

feat:refine the stage viewer size update presentation

---

spx-gui/src/components/spx-stage/SpxStage.vue
spx-gui/src/components/stage-viewer/StageViewer.vue
spx-gui/src/store/modules/sprite/index.ts

#140 
Resolve that controller still exists when switching project

fix:correct update the controller of stage viewer after importing the new project

---

spx-gui/src/components/spx-stage/SpxStage.vue
spx-gui/src/util/dom.ts

fix:abstract dom size observe logic

---

spx-gui/src/class/project.ts
spx-gui/src/components/top-menu/TopMenu.vue
spx-gui/src/store/modules/project/index.ts

feat: project io

---

spx-gui/src/class/asset-base.ts
spx-gui/src/class/backdrop.ts
spx-gui/src/class/project.ts
spx-gui/src/class/sound.ts
spx-gui/src/class/sprite.ts
spx-gui/src/components/spx-stage/SpxStage.vue
spx-gui/src/components/stage-viewer-demo/StageViewerDemo.vue

chore: modifier

---

spx-gui/src/components/sprite-list/SpriteList.vue
spx-gui/src/components/spx-code-editor/SpxCodeEditor.vue
spx-gui/src/language/index.ts
spx-gui/src/store/modules/editor/index.ts
spx-gui/src/store/modules/sprite/index.ts

Once the user edits the default entryCode, the entryCode of project will be set to project and the project will not generate a new default entryCode 
If the project is imported by the user, the entryCode will not be generated automatically because of the existence of entrycode

feat:support entrycode edit

---

spx-gui/src/api/project.ts
spx-gui/src/class/project.ts
spx-gui/src/components/project-list/ProjectCard.vue
spx-gui/src/components/project-list/ProjectList.vue

fix: modify code of project list

---

spx-gui/src/components/code-editor/CodeEditor.vue
spx-gui/src/components/code-editor/language.ts
spx-gui/src/components/code-editor/register.ts

Test and improve code editor module

---

spx-gui/src/class/asset-list.ts
spx-gui/src/store/modules/sprite/index.ts

fix:default current sprite & zorder update

---

README.md
docs/api-doc/api-document.md
docs/contribution/contribution.md
docs/installation/installation.md

Feat: readme, installation, contribution docs

---

spx-gui/src/class/asset-list.ts
spx-gui/src/class/backdrop.ts
spx-gui/src/class/project.ts
spx-gui/src/class/sound.ts
spx-gui/src/class/sprite.ts
spx-gui/src/store/modules/project/index.ts
spx-gui/src/util/class.ts
spx-gui/src/widgets/widget/spx-runner/SpxRunner.ce.vue

可以运行但TypeScript会报错,似乎是由于ref过滤掉了private函数.目前将一些project内的函数标记为私有.

refactor: make project reactive

---

spx-gui/package-lock.json
spx-gui/package.json
spx-gui/src/components/editor/stage/RunnerContainer.vue
spx-gui/src/components/editor/stage/SpxStage.vue
spx-gui/src/components/project-runner/IframeDisplay.vue
spx-gui/src/components/project-runner/ProjectRunner.vue
spx-gui/src/components/project-runner/RunnerContainer.vue
spx-gui/src/components/project-runner/__snapshots__/ProjectRunner.test.ts.snap

feat: project runner modal

---

spx-gui/src/components/top-menu/UserAvatar.vue

refreshing is no longer required

do not refresh on signout

---

spx-backend/go.mod
spx-backend/go.sum
spx-backend/internal/controller/controller.go
spx-backend/internal/controller/controller_test.go
spx-gui/package-lock.json
spx-gui/package.json
spx-gui/src/App.vue
spx-gui/src/components/project-list/ProjectCard.vue
spx-gui/src/components/project/ProjectCreate.vue
spx-gui/src/components/project/index.ts
spx-gui/src/components/top-menu/TopMenu.vue
spx-gui/src/stores/project.ts
spx-gui/src/utils/exception.ts
spx-gui/src/utils/form.ts
spx-gui/src/utils/i18n/README.md
spx-gui/src/utils/i18n/index.ts
spx-gui/tsconfig.app.json

fix #268 
* Project creating at frontend
* Project name check at backend
* Upgrade naive-ui for imperative API of modal
* Remove `FunctionLocaleMessage` for `utils/i18n`
* Extract `utils/form` to wrap naive-ui form's ugly APIs

New project creating

---

spx-gui/src/models/common/cloud.ts
spx-gui/src/models/common/file.ts
spx-gui/src/models/costume.ts
spx-gui/src/utils/file.ts

* submit mimeType when uploading file, fix https://github.com/goplus/builder/pull/289#discussion_r1558932601
* remove useless img remove

Preserve file mimeType when uploading

---

spx-gui/src/components/editor/EditorHomepage.vue
spx-gui/src/components/top-nav/TopNav.vue
spx-gui/src/models/backdrop.ts
spx-gui/src/models/common/local.ts
spx-gui/src/models/costume.ts
spx-gui/src/models/project.ts
spx-gui/src/models/sound.ts
spx-gui/src/models/sprite.ts
spx-gui/src/models/stage.ts
spx-gui/src/widgets/spx-runner/SpxRunner.ce.vue

Local Cache Saving & Restoring

---

docs/installation/installation.md
spx-backend/.gitignore

Minor issues found at work #297.

docs(installation): fix spx-backend build instructions

---

spx-gui/src/components/editor/ProjectEditor.vue
spx-gui/src/components/editor/preview/EditorPreview.vue

Implement basic UI for EditorPreview (formerly SpxStage)

---

spx-gui/src/components/project/ProjectCreateModal.vue
spx-gui/src/components/project/index.ts

Redesign ProjectCreateModal (formerly ProjectCreate) using UIFormModal

---

spx-gui/src/components/editor/EditorHomepage.vue
spx-gui/src/components/project/ProjectItem.vue
spx-gui/src/components/project/ProjectList.vue
spx-gui/src/components/project/ProjectOpenModal.vue
spx-gui/src/components/project/bg.svg
spx-gui/src/components/top-nav/TopNav.vue

UI: Editor home

---

spx-gui/src/components/editor/EditorHomepage.vue

UI: Fix "New Project" button in EditorHomepage

---

spx-gui/src/components/editor/EditorHomepage.vue
spx-gui/src/components/editor/panels/sprite/SpriteBasicConfig.vue
spx-gui/src/components/editor/preview/EditorPreview.vue
spx-gui/src/components/editor/sound/SoundEditor.vue
spx-gui/src/components/project/ProjectCreateModal.vue
spx-gui/src/components/project/ProjectItem.vue
spx-gui/src/components/project/runner/RunnerContainer.vue
spx-gui/src/components/ui/UIConfigProvider.vue
spx-gui/src/components/ui/modal/UIFormModal.vue
spx-gui/src/components/ui/modal/UISearchableModal.vue

UI: Fix title colors

---

spx-backend/internal/controller/controller.go
spx-backend/internal/utils/fmtcode/fmtcode.go

API `/util/fmt` does not work as expected in env test. Add log to help troubleshoot.

Add log for API `/util/fmt`

---

spx-gui/src/components/asset/scratch/LoadFromScratch.vue
spx-gui/src/components/asset/scratch/LoadFromScratchModal.vue
spx-gui/src/components/editor/EditorHomepage.vue
spx-gui/src/components/editor/sound/SoundRecorder.vue
spx-gui/src/components/project/runner/RunnerContainer.vue
spx-gui/src/components/ui/modal/UIFormModal.vue

- **fix: recorder title center**
- **fix: image overflow in LoadFromScratch**

fix: ui bugs & inconsistency and dialog for cache

---

Dockerfile
nginx.conf

#385 introduced problem in k8s, external requests are not correctly handled. We adjust nginx config to fix it.

fix nginx in docker

---

spx-gui/src/components/editor/preview/EditorPreview.vue
spx-gui/src/components/editor/preview/stage-viewer/StageViewer.vue

UI: Fix StageViewer in EditorPreview

---

spx-gui/src/components/ui/menu/UIMenuGroup.vue
spx-gui/src/components/ui/menu/UIMenuItem.vue

Update `UIMenu(Group|Item)` style

---

spx-gui/src/components/project/ProjectCreateModal.vue
spx-gui/src/components/ui/UITextInput.vue
spx-gui/src/components/ui/form/UIFormItem.vue

Update form validation & tip style

---

spx-gui/src/components/top-nav/TopNav.vue

参考 figma 的做法，header 通过 flex 分成三块：左、中、右，给左跟右相同的 flex-basis 来让中部内容居中，好像一定程度上可以兼顾可维护性跟内容重叠（overflow）的问题

Optimize center behavior for `TopNav`

---

spx-gui/src/components/asset/scratch/LoadFromScratch.vue
spx-gui/src/components/editor/EditorHomepage.vue
spx-gui/src/components/ui/modal/UIFormModal.vue
spx-gui/src/components/ui/modal/UIModalClose.vue
spx-gui/src/components/ui/modal/UISearchableModal.vue

- **fix: modal title center**
- **fix: i18n**

fix: modal title center & i18n

---

spx-gui/src/components/asset/index.ts
spx-gui/src/components/asset/library/AssetLibraryModal.vue
spx-gui/src/components/asset/scratch/LoadFromScratch.vue
spx-gui/src/components/editor/ProjectEditor.vue
spx-gui/src/components/editor/code-editor/CodeEditor.vue
spx-gui/src/components/editor/code-editor/code-text-editor/snippets.ts
spx-gui/src/components/editor/panels/common/PanelHeader.vue
spx-gui/src/components/editor/panels/sound/SoundsPanel.vue
spx-gui/src/components/editor/panels/sprite/SpriteBasicConfig.vue
spx-gui/src/components/editor/panels/sprite/SpritesPanel.vue
spx-gui/src/components/editor/preview/EditorPreview.vue
spx-gui/src/components/editor/preview/stage-viewer/SpriteItem.vue
spx-gui/src/components/editor/preview/stage-viewer/StageViewer.vue
spx-gui/src/components/editor/sound/SoundRecorder.vue
spx-gui/src/components/editor/sound/SoundRecorderModal.vue
spx-gui/src/components/top-nav/TopNav.vue
spx-gui/src/components/ui/UIDropdown.vue
spx-gui/src/components/ui/modal/UIModal.vue
spx-gui/src/components/ui/modal/UISearchableModal.vue
spx-gui/src/models/common/asset.ts
spx-gui/src/utils/utils.ts

* Details of Sprite size & pos input in sprites-panel
* Style details for some modals & popup
* Remove details of code snippets
* Add confirm dialog before importing project file

Details fix for UI review

---

spx-gui/src/components/ui/form/UIFormItem.vue
spx-gui/src/components/ui/form/UIFormItemInternal.vue
spx-gui/src/components/ui/form/ctrl.ts
spx-gui/src/components/ui/modal/UIFormModal.vue
spx-gui/src/components/ui/modal/UIFullScreenModal.vue
spx-gui/src/models/common/asset.ts

* Optimize form validation trigger logic, close #419 
* Fix `auto-focus` behavior for `FormModal` & `FullScreenModal`
* Asset name validation update, part of #418

Optimize form validation trigger logic

---

spx-gui/src/components/ui/UIButton.vue
spx-gui/src/components/ui/UIIconButton.vue

UI: Fix focus outline-color for buttons

---

spx-gui/src/components/project/ProjectItem.vue
spx-gui/src/components/project/ProjectList.vue
spx-gui/src/models/common/cloud.ts
spx-gui/src/models/project.ts

Optimize project list load behavior

---

spx-gui/src/components/editor/EditorHomepage.vue
spx-gui/src/components/ui/dialog/UIConfirmDialog.vue
spx-gui/src/components/ui/modal/UIModal.vue
spx-gui/src/models/common/disposable.ts
spx-gui/src/models/project.ts

- **prevent confirm modals from closing on backdrop clicks**
- **fix: project saved upon disposing**

fix: prevent backdrop click from closing the confirm dialog & prevent the project from saving upon dispose

---

spx-gui/src/components/asset/library/AssetLibraryModal.vue
spx-gui/src/components/asset/scratch/LoadFromScratch.vue
spx-gui/src/components/editor/panels/sprite/SpritesPanel.vue
spx-gui/src/components/project/ProjectCreateModal.vue
spx-gui/src/components/project/runner/RunnerContainer.vue
spx-gui/src/models/sprite.ts
spx-gui/src/models/stage.ts

* Add Sprite `autoFit` to get better default size & position for new sprites, close #416

autoFit for sprites

---

spx-gui/src/components/editor/panels/EditorPanels.vue

Remember sprite/sound selection when switching panels

---

spx-gui/src/components/editor/EditorHeader.vue
spx-gui/src/components/editor/stage/StageEditor.vue

* top-right border-radius for `EditorHeader`
* color for `StageEditor`

Fix editor header style

---

spx-gui/vercel.json

Fixes #439
---
- Headers: https://vercel.com/docs/projects/project-configuration#headers
- Legacy SPA Fallback: https://vercel.com/docs/projects/project-configuration#legacy-spa-fallback

spx-gui: update vercel.json to replace deprecated routes field

---

spx-gui/src/components/ui/UIInfiniteScrollList.vue

UI(UIInfiniteScrollList): Remove min-height for list

---

spx-gui/src/components/editor/code-editor/code-text-editor/snippets.ts

fix: Duplicate snippet changeSize

---

spx-gui/.env
spx-gui/middleware.ts
spx-gui/package-lock.json
spx-gui/package.json

Fixes #414
---
- https://vercel.com/docs/functions/edge-middleware/middleware-api

spx-gui: utilize Vercel Edge Middleware to proxy API requests

---

spx-backend/cmd/spx-backend/gop_autogen.go
spx-backend/cmd/spx-backend/project_yap.gox
spx-backend/internal/controller/controller.go
spx-backend/internal/utils/fmtcode/fmtcode.go
spx-gui/src/apis/util.ts
spx-gui/src/components/editor/code-editor/code-text-editor/CodeTextEditor.vue

spx-backend: refactor /util/fmt

---

spx-backend/internal/controller/controller.go
spx-gui/src/apis/util.ts
spx-gui/src/models/common/cloud.ts

spx-backend: refactor /util/upinfo

---

spx-backend/cmd/spx-backend/gop_autogen.go
spx-backend/cmd/spx-backend/project_yap.gox
spx-backend/internal/controller/controller.go
spx-gui/src/apis/util.ts
spx-gui/src/models/common/asset.ts
spx-gui/src/models/common/cloud.ts
spx-gui/src/models/project.ts

Switch downloading Kodo objects from unsigned to signed URLs

---

spx-gui/src/components/top-nav/TopNav.vue
spx-gui/src/models/project.ts
spx-gui/src/models/sprite.ts
spx-gui/src/models/stage.ts

* handle exception for `TopNav` operations
* handle exception for Project `load` in `loadGbpFile`
* warnings for unsupported spx features

optimize details for project file import

---

spx-gui/src/components/project/runner/RunnerContainer.vue

fix: console message wrap

---

spx-gui/src/components/editor/code-editor/code-text-editor/snippets/index.ts
spx-gui/src/components/editor/code-editor/code-text-editor/snippets/spx.ts
tools/ispx/go.mod
tools/ispx/go.sum
tools/ispx/pkg/github.com/goplus/spx/export.go

close #443 
* Upgrade `spx` for `tools/ispx`
* Use `"foo"` instead of `foo` for sound snippet

Simplify process to add & play sound

---

spx-backend/internal/controller/controller.go
spx-gui/src/apis/asset.ts
spx-gui/src/apis/common/index.ts
spx-gui/src/apis/project.ts
spx-gui/src/apis/util.ts
spx-gui/src/components/project/ProjectCreateModal.vue
spx-gui/src/models/common/asset.ts
spx-gui/src/models/common/cloud.ts

spx-backend: store only object keys in the DB

---

spx-gui/src/utils/file.ts

UI: Prevent selection of oversized files

---

spx-gui/src/components/asset/library/AssetAddModal.vue
spx-gui/src/components/asset/library/AssetLibraryModal.vue
spx-gui/src/components/asset/library/BackdropPreview.vue
spx-gui/src/components/asset/library/SoundPreview.vue
spx-gui/src/components/asset/library/SpritePreview.vue
spx-gui/src/components/editor/EditorHomepage.vue
spx-gui/src/components/editor/FormatButton.vue
spx-gui/src/components/editor/panels/common/PanelItem.vue
spx-gui/src/components/editor/panels/sound/SoundItem.vue
spx-gui/src/components/editor/panels/sound/SoundsPanel.vue
spx-gui/src/components/editor/panels/sprite/SpriteBasicConfig.vue
spx-gui/src/components/editor/panels/sprite/SpriteItem.vue
spx-gui/src/components/editor/panels/sprite/SpritesPanel.vue
spx-gui/src/components/editor/panels/stage/StagePanel.vue
spx-gui/src/components/editor/sound/DumbSoundPlayer.vue
spx-gui/src/components/editor/sound/SoundEditor.vue
spx-gui/src/components/ui/UIDropdown.vue
spx-gui/src/components/ui/UITag.vue
spx-gui/src/components/ui/menu/UIMenuItem.vue
spx-gui/src/utils/utils.ts

close #461 
* Add asset to (personal) asset library
* Choose asset from (personal) asset library
* Adjust text for adding-asset:
- "Choose" -> "Choose from asset lirbary"
- "Upload" -> "Select local file"

Personal asset library

---

spx-gui/.prettierrc

这个主要是我自己偏好用 tabs 来缩进，如果不改这里的话那我就得改全局的或者单独在其他项目里设置，怪麻烦的😂

spx-gui: set useTabs to false in .prettierrc

---

spx-gui/src/components/editor/common/EditorItemDetail.vue
spx-gui/src/components/editor/common/EditorList.vue
spx-gui/src/components/editor/sprite/CostumesEditor.vue
spx-gui/src/components/editor/stage/BackdropsEditor.vue

UI details for adding backdrop & costume

---

spx-gui/src/components/editor/sound/SoundEditor.vue
spx-gui/src/components/editor/sound/WavesurferWithRange.vue
spx-gui/src/components/editor/sound/wavesurfer.ts

- **fix: progress wave color**
- **fix: play on save/cancel**

auto play after save / wave colorcould

---

spx-gui/src/models/common/cloud.ts

This change also removes legacyObjects related code in getFiles.
Fixes #539

Avoid empty call to makeObjectUrls

---

spx-backend/cmd/spx-backend/gop_autogen.go
spx-backend/cmd/spx-backend/main.yap

spx-backend: add graceful shutdown support

---

.github/workflows/release.yml

Add status-check polling to release.yml for async tasks

---

spx-gui/src/components/editor/preview/EditorPreview.vue
spx-gui/src/components/editor/sound/SoundEditor.vue
spx-gui/src/components/editor/sound/WavesurferWithRange.vue
spx-gui/src/components/project/ProjectItem.vue
spx-gui/src/components/ui/UIButton.vue
spx-gui/src/components/ui/UIButtonGroupItem.vue
spx-gui/src/utils/audio.ts

- **close UIButtonGroup details #559**
- **close Project list tooltip #560**

fix ui issues

---

spx-gui/src/components/editor/code-editor/CodeEditor.vue

Adjust order of tool-categories in CodeEditor

---

spx-gui/src/components/editor/preview/stage-viewer/SpriteTransformer.vue

Optimize transformer config for `StageViewer`

---

spx-backend/internal/controller/asset_test.go
spx-backend/internal/controller/project_test.go
spx-backend/internal/controller/util_test.go
spx-backend/internal/model/asset.go
spx-backend/internal/model/asset_test.go
spx-backend/internal/model/project.go
spx-backend/internal/model/project_test.go
spx-backend/internal/model/query.go
spx-backend/internal/model/query_test.go
spx-backend/internal/model/scan.go
spx-backend/internal/model/scan_test.go

spx-backend: implement generic model INSERT and UPDATE

---

Dockerfile

Reverts goplus/builder#575
---
@CarlJi 
https://github.com/goplus/builder/actions/runs/9400933374/job/25891600840

Revert "ci: switching to qiniu internal image registry due to external network issue"

---

Dockerfile
scripts/pr-preview.sh

ci: make image address as arg since the dockerfile is being used both in github runner and qiniu internal env

---

spx-gui/src/apis/common/index.ts
spx-gui/src/components/project/ProjectCreateModal.vue
spx-gui/src/models/common/asset.ts
spx-gui/src/models/common/cloud.ts

Save text files directly to the DB for performance

---

spx-gui/src/models/animation.ts

* fix animation duration
* add method `ungroup`
* other details update

Update model `Animation`

---

spx-backend/cmd/spx-backend/gop_autogen.go
spx-backend/cmd/spx-backend/post_util_fileurls.yap
spx-gui/src/components/project/index.ts

fix(spx-gui): save to cloud after sharing project and remove login requirement for making signed web URLs

---

spx-gui/src/components/editor/sprite/AnimationItem.vue
spx-gui/src/components/editor/sprite/AnimationRemoveModal.vue
spx-gui/src/components/editor/sprite/animation/AnimationPlayer.vue
spx-gui/src/components/editor/sprite/animation/MuteSwitch.vue

- **feat: remove costume & preload frames**
- **fix: use ref for muted**

Preload frames & audio / removal modal

---

spx-gui/src/components/asset/animation/GroupCostumesModal.vue
spx-gui/src/components/editor/sprite/animation/AnimationPlayer.vue
spx-gui/src/models/common/disposable.ts
spx-gui/src/utils/file.ts

- **refactor preload / modify translation**
- **do not update on zero duration**

refactor preload / modify translation

---

docs/product/animation.md
docs/product/animation.zh.md
docs/product/index.md
docs/product/index.zh.md
docs/product/widget.md
docs/product/widget.zh.md

* Add docs in english
* Add docs for Widget, see details in #578

Product doc for Widget

---

Dockerfile

- Replaced manual installation with pre-built images for Go+ and Nginx.
- Modified CMD to enable log output.

dockerfile: utilize pre-built images for Go+ and Nginx

---

spx-gui/src/components/editor/EditorHomepage.vue

See https://github.com/vuejs/rfcs/blob/master/active-rfcs/0037-router-return-guards.md#motivation

spx-gui: avoid calling `next` within `router.beforeEach`

---

spx-gui/src/components/asset/library/AssetLibrary.vue
spx-gui/src/components/asset/library/AssetLibraryModal.vue
spx-gui/src/components/asset/library/SearchContextProvider.vue

This PR introduces a context provider for asset search parameters and results, and refactors the asset library component.
- Extracted asset library logic from AssetLibraryModal.vue to AssetLibrary.vue.
- Added SearchContextProvider to manage search parameters and results context.
- Updated components to use the new context provider for asset search.
- Removed outdated search logic from AssetLibrary.

feat(spx-gui): add context provider for asset search parameters and results

---

spx-gui/src/models/runtime.ts

- Add a runtime error class for handle froject runtime error console.
- With callback to mention other part.
- Only save current runtime error.
- May support more types of log.
- Still lake of test.

feat: runtime error class.

---

spx-gui/src/apis/asset.ts
spx-gui/src/components/asset/library/AssetLibrary.vue
spx-gui/src/components/asset/library/AssetList.vue
spx-gui/src/components/asset/library/BackdropItem.vue
spx-gui/src/components/asset/library/SearchContextProvider.vue
spx-gui/src/components/asset/library/SoundItem.vue
spx-gui/src/components/asset/library/SpriteItem.vue
spx-gui/src/components/ui/block-items/UIBlockItem.vue
spx-gui/src/models/common/asset.ts

This PR focuses on improving the asset library page with the following key changes:

Improve asset library with pagination and virtual list

---

spx-gui/src/models/project/index.ts

Add a get function for project class to ensure filesHash can get from outside.

feat: add getter for project class.

---

spx-backend/internal/controller/llm.go

[From#672#AI](https://github.com/goplus/builder/pull/672/files#diff-cabb8cc9c6f8dd3d9d698b2205ffa917addca2f6e8031f7e59c35e005412159e)

feat: Add a AI backend support

---

spx-gui/src/components/asset/library/AssetItem.vue
spx-gui/src/components/asset/library/AssetLibrary.vue
spx-gui/src/components/asset/library/AssetLibraryModal.vue
spx-gui/src/components/asset/library/AssetList.vue
spx-gui/src/components/asset/library/LibrarySelect.vue
spx-gui/src/components/asset/library/LibraryTree.vue
spx-gui/src/components/asset/library/SearchContextProvider.vue
spx-gui/src/components/asset/library/details/DetailModal.vue
spx-gui/src/components/asset/library/details/SpriteDetailDisplay.vue
spx-gui/src/components/ui/UIConfigProvider.vue

- Add `Favorite` and `Add to project` functionality to detail page.
- Move detail page into asset library modal and add transition effect to reduce ui complexity.
- Fix some styling issues:
- Adjusted borderRadius of Checkbox in library tree selector.
- Adjusted width and height styles of AssetLibraryModal and Preview in detail page for better appearance.
- Adjusted the style of library tree selector to avoid overstretching the modal.
- Adjusted some i18n text.

Optimize Asset library and Detail page styles and functionality

---

spx-backend/cmd/spx-backend/get_asset_liked_list
spx-backend/cmd/spx-backend/post_user_liked.yap
spx-backend/internal/controller/user_asset.go

Feat:liked api

---

spx-gui/src/apis/asset.ts
spx-gui/src/components/asset/library/AssetLibrary.vue

This pull request implements search suggestions feature for asset list.
- Update search text input ui to use search suggestions
- Add search suggestions api with temporary implementation
Search suggestions api is not implemented yet.
Currently, the suggestions are retrieved from asset list api.

feat(spx-gui): asset search suggestions

---

spx-gui/src/components/editor/code-editor/CodeEditor.vue
spx-gui/src/components/editor/code-editor/chat-bot.ts
spx-gui/src/components/editor/code-editor/coordinators/index.ts
spx-gui/src/components/editor/stage/StageEditor.vue

rename some interface name like `ai-chat` to `chat-bot`, `models` to `abilities`, etc.

chore(spx-gui): rename UI interface name

---

spx-backend/cmd/spx-backend/delete_llm_chat_#id.yap
spx-backend/cmd/spx-backend/post_llm_chat.yap
spx-backend/cmd/spx-backend/post_llm_chat_#id.yap
spx-backend/cmd/spx-backend/post_llm_task.yap
spx-backend/internal/controller/llm.go
spx-gui/src/apis/llm.ts

feat: create ai port at frontend & backend.

feat: create ai port at frontend & backend.

---

spx-gui/src/components/ui/UIDropdown.vue

spx-gui(UIDropdown): fix `NPopover.setShow` not triggering `on-update:show`

---

spx-backend/internal/controller/user_asset.go
spx-backend/internal/model/asset.go
spx-backend/internal/model/asset_test.go
spx-backend/internal/model/category_test.go
spx-backend/internal/model/query_test.go
spx-backend/internal/model/user_asset.go
spx-backend/internal/model/user_asset_test.go

add model layer unit test.
The test cover from 76.3% to 91.4%

Test:add unit test

---

spx-backend/cmd/spx-backend/get_user_history_list.yap
spx-backend/cmd/spx-backend/get_user_liked_list.yap
spx-backend/cmd/spx-backend/gop_autogen.go
spx-backend/internal/controller/user_asset.go

resolve issue of null user asset list

Hot fix/use asset list

---

spx-gui/src/components/editor/code-editor/ui/EditorSidebar.vue
spx-gui/src/components/editor/code-editor/ui/icons/collapse.svg

this is pr about add collapse button now sidebar can collapse and expand

feat(spx-gui): add sidebar collapse and expand function

---

spx-gui/src/components/editor/code-editor/EditorUI.ts
spx-gui/src/components/editor/code-editor/ui/code-text-editor/CodeTextEditor.vue
spx-gui/src/components/editor/code-editor/ui/features/completion-menu/completion-item-cache.ts
spx-gui/src/components/editor/code-editor/ui/features/completion-menu/completion-menu.ts

- fix when typing rapidly not showing completion items.
- fix duplicate showing code preview.

feat(spx-gui): fix completion duplicate code preview

---

spx-gui/src/components/editor/panels/common/CommonPanel.vue

fix(CommonPanel): make expansion transition smoother

---

spx-gui/index.html

- Added `dns-prefetch` and `preconnect` links for better performance optimization.
- Included `description` and `keywords` meta tags for better SEO.
Fixes #713
---

refactor(index.html): improve meta tags and utilize DNS prefetching

---

tools/compiler/internal/ast.go
tools/compiler/internal/definition.go
tools/compiler/internal/diagnostics.go
tools/compiler/internal/errors.go
tools/compiler/internal/setups.go
tools/compiler/internal/types.go
tools/compiler/static/parent.html

- Change the way to get user's code function parameter.
- Change some function name and struct name.

feat`WASM compiler`: Change the way to get user's code function parameter.  

---

spx-gui/src/apis/aigc.ts
spx-gui/src/components/asset/library/AIAssetItem.vue
spx-gui/src/components/asset/library/AssetLibrary.vue
spx-gui/src/components/asset/library/AssetList.vue
spx-gui/src/components/asset/library/ai/AIPreviewModal.vue

This pull request added a aigc task handler to handle sync or async ai-generation task, and provided a
same interface for retrieve generation result from different kind of tasks.
For async task, the handler will call `action` to start a generation request and poll the status with given poll function. While for sync task, the handle will just wait for the result from `action` and consider it as finished.
- The result of the task will be stored in the `result` field.
- Adjust the `pollingInterval` and `pollingLimit` to control the polling behavior.
- `action`: The action to request AI-generation
- `args`: Arguments for the `action`
- `pollFn`: A function to poll the status of the AI-generation.
- if `pollFn` is not provided, the task will be considered as finished after the `action` is …

feat: Add a aigc task handler for adapt to sync or async task

---

spx-gui/src/components/asset/library/AssetLibraryModal.vue
spx-gui/src/components/editor/panels/sprite/config/SpriteBasicConfig.vue
spx-gui/src/components/editor/stage/widget/detail/MonitorDetail.vue
spx-gui/src/components/ui/form/UIFormItem.vue
spx-gui/src/models/project/index.test.ts
spx-gui/src/models/project/index.ts
spx-gui/src/utils/utils.ts

This also removes `@utils/utils.debounce` in favor of `lodash.debounce`.

refactor(Project): ensure pending auto-save is cancelled after `dispose` is called

---

spx-gui/index.html
spx-gui/src/components/asset/library/AssetLibraryModal.vue
spx-gui/src/components/editor/panels/common/CommonPanel.vue
spx-gui/src/components/editor/panels/sprite/config/SpriteBasicConfig.vue
spx-gui/src/components/editor/sprite/AnimationEditor.vue
spx-gui/src/components/editor/stage/widget/detail/MonitorDetail.vue
spx-gui/src/components/project/ProjectCreateModal.vue
spx-gui/src/components/ui/UINumberInput.vue
spx-gui/src/components/ui/UITextInput.vue
spx-gui/src/components/ui/form/UIFormItem.vue
spx-gui/src/models/animation.test.ts
spx-gui/src/models/project/history.ts
spx-gui/src/models/project/index.test.ts
spx-gui/src/models/project/index.ts
spx-gui/src/utils/disposable.ts
spx-gui/src/utils/exception.ts
spx-gui/src/utils/utils.ts

* Related project: https://github.com/orgs/goplus/projects/6/views/1

Release v1.4.1

---

spx-gui/src/components/asset/library/AssetLibrary.vue
spx-gui/src/components/asset/library/LibraryTree.vue

Adjust some style issues of library model.
- Default to expand all tree items in category select.
- Adjust asset list height in full-screen model.

style: adjust style of asset library model.

---

spx-gui/src/components/project/runner/RunnerContainer.vue

fix #807
* Optimize console style for complex log output
* Adjust font-size & padding based on [design](https://www.figma.com/design/vmDy0ROUDDFL22UjLljUk0/Go%2B-Builder-%E7%95%8C%E9%9D%A2%E8%AE%BE%E8%AE%A1?node-id=1-2675&m=dev)

Optimize console log style

---

spx-backend/cmd/spx-backend/delete_llm_chat_#id.yap
spx-backend/cmd/spx-backend/gop_autogen.go
spx-backend/cmd/spx-backend/post_llm_chat.yap
spx-backend/cmd/spx-backend/post_llm_chat_#id.yap
spx-backend/cmd/spx-backend/post_llm_task.yap
spx-backend/internal/controller/llm.go
spx-backend/internal/controller/llm_test.go

- Fix yap bugs.
- Fix llm `StartTask`, `DeleteChat`, `NextChat`, `StartChat` required a pointer type as an argument.

fix`SPX Backend`: Fix llm bugs.

---

spx-gui/src/apis/aigc.ts
spx-gui/src/apis/asset.ts
spx-gui/src/components/asset/library/AIAssetItem.vue
spx-gui/src/components/asset/library/AssetList.vue
spx-gui/src/components/asset/library/AssetRenameModal.vue
spx-gui/src/components/asset/library/ai/AIPreviewModal.vue
spx-gui/src/models/aigc.ts
spx-gui/src/utils/exception.ts

This pull request includes several commits that fix a state display bug and add asset transfer logic. 
1. The "fix: fix state display bug" commit addresses a bug related to the display of asset states. 
2. The "fix: add ai asset transfer logical" commit adds logic for transferring AI assets. 
3. The "feat: add function to handle no more assets in AssetList.vue" commit adds a function to handle cases where there are no more assets in the AssetList component. 
4. The "feat: add useRetryHandle for action retry" commit adds a function for retrying failed actions. 
5. The "fix: some param adjust" commit makes some parameter adjustments.

Feat: Fix state display bug and add asset transfer logic

---

spx-gui/src/components/asset/library/ai/AIBackdropEditor.vue
spx-gui/src/components/asset/library/ai/AIPreviewModal.vue
spx-gui/src/components/asset/library/ai/ImageEditor/useCenterPosition.ts

Changes:
- Add undo and redo functionality to AI backdrop editor
- Update saving interaction for AI backdrop editor

feat: Add undo and redo functionality to AI backdrop editor

---

spx-gui/src/components/editor/code-editor/ui/EditorMenu.vue
spx-gui/src/components/editor/code-editor/ui/features/completion-menu/CompletionMenuComponent.vue
spx-gui/src/components/editor/code-editor/ui/features/selection-menu/SelectionMenuComponent.vue

this pr is about refactor `EdtiorMenu.vue` props, if other component it can directly update `EdtiorMenu.vue` css style by `:deep()`

feat(spx-gui): refactor `EditorMenu.vue` props

---

spx-gui/src/components/asset/index.ts
spx-gui/src/components/asset/library/AIAssetItem.vue
spx-gui/src/components/asset/library/AssetRenameModal.vue
spx-gui/src/components/asset/library/ai/AIPreviewModal.vue

this pr introduce a rename modal,which user can change the ai asset name to make it more readable

Feat: Rename

---

tools/compiler/internal/base.go
tools/compiler/internal/completion.go
tools/compiler/internal/definition.go
tools/compiler/internal/diagnostics.go
tools/compiler/static/parent.html

fix`WASM Compiler`: Change the way to find scope.

---

spx-gui/.env.prod
spx-gui/src/components/asset/preprocessing/PreprocessModal.vue
spx-gui/src/components/editor/stage/backdrop/BackdropDetail.vue

* fix #839 
* fix #841 
* Commit `.env.prod` to simplify development with online backend

Fix detail problems

---

spx-gui/src/components/editor/code-editor/EditorUI.ts
spx-gui/src/components/editor/code-editor/compiler.ts
spx-gui/src/components/editor/code-editor/coordinators/index.ts
spx-gui/src/components/editor/code-editor/document.ts
spx-gui/src/components/editor/code-editor/tools/gop.ts
spx-gui/src/components/editor/code-editor/tools/index.ts
spx-gui/src/components/editor/code-editor/ui/CodeEditorUI.vue
spx-gui/src/components/editor/code-editor/ui/EditorSidebar.vue
spx-gui/src/components/editor/code-editor/ui/ToolItem.vue
spx-gui/src/components/editor/code-editor/ui/common/index.ts

this pr is about implment outer interface,  update toolCategory to inputItemCategory, hover document is in progressing.

feat(spx-gui): update toolCategory to inputItemCategory

---

spx-gui/src/components/asset/index.ts
spx-gui/src/components/asset/preprocessing/PreprocessModal.vue
spx-gui/src/components/ui/block-items/UIBlockItem.vue
spx-gui/src/models/costume.ts
spx-gui/src/models/sprite.ts

* Optimize costumes position, close #850
* Fix css var syntax error for `PreprocessModal.vue`
* Fix `BlockItem` size

Optimize costumes position

---

spx-backend/cmd/spx-backend/get_user_rate_#id.yap
spx-backend/cmd/spx-backend/gop_autogen.go
spx-backend/cmd/spx-backend/post_user_rate_#id.yap
spx-backend/internal/controller/rate.go
spx-backend/internal/model/asset.go
spx-backend/internal/model/rate.go
spx-backend/internal/model/rate_test.go
spx-gui/src/apis/asset.ts
spx-gui/src/components/asset/library/AIAssetItem.vue
spx-gui/src/components/asset/library/AssetItem.vue
spx-gui/src/components/asset/library/AssetList.vue
spx-gui/src/components/asset/library/LibraryMenu.vue
spx-gui/src/components/asset/library/LibraryTree.vue
spx-gui/src/components/asset/library/SearchContextProvider.vue
spx-gui/src/components/asset/library/details/SpriteCarousel.vue
spx-gui/src/components/asset/library/reviews/AssetRate.vue

This pull request addresses several UI issues and improvements in the asset library section:
- Fix sprite animation carousel issue where the costume is not visible when there is only one model in the carousel.
- Fix Rating Data Handling and Storage:
- Removed user parameters when fetching ratings.
- Fixed the precision of returned ratings.
- Stored rating records using user ID instead of username.
- Prevented users from rating the same asset multiple times.
- Change Asset List and Item Styles:
- Removed the discordant gradient background.
- Synchronized the number of columns in the asset list.
- Displayed the number of favorites and ratings on asset item information.
- Added icons and public asset items to the category switch menu (LibraryMenu).
- Adjusted the styles and layout of the …

Fix and Adjust UI Issues in Asset Library

---

spx-gui/src/components/editor/code-editor/coordinators/index.ts
spx-gui/src/components/editor/code-editor/tools/common.ts
spx-gui/src/components/editor/code-editor/tools/gop.ts
spx-gui/src/components/editor/code-editor/tools/index.ts
spx-gui/src/components/editor/code-editor/tools/spx.ts
tools/compiler/internal/completion.go
tools/compiler/internal/definition.go

- feat: add tokenID and tokenPkg into type Tool.
- feat: add usageId into type usage.
- feat: add property for each tool item.

feat`SPX Frontend`: Make type Tool -> Token to prepare get data from compiler and document.

---

tools/compiler/internal/base.go
tools/compiler/internal/completion.go
tools/compiler/internal/fsx.go
tools/compiler/internal/setups.go
tools/compiler/internal/types.go
tools/compiler/js.go
tools/compiler/static/index.js
tools/compiler/static/parent.html

feat: Add multiple file support.

feat`WASM Compiler`: add multiple file support.

---

spx-gui/src/components/editor/code-editor/coordinators/index.ts
tools/compiler/internal/base.go
tools/compiler/static/index.js

fix: fix the bug of vue build error.
fix: add error print.

fix: fix the error of frontend and wasm.

---

spx-gui/src/assets/compiler/index.html
spx-gui/src/components/editor/code-editor/CodeEditor.vue
spx-gui/src/components/editor/code-editor/compiler.ts
spx-gui/src/components/editor/code-editor/coordinators/index.ts
spx-gui/src/components/editor/code-editor/ui/common/style-sheet-content.ts
spx-gui/src/components/editor/code-editor/ui/features/attention-hint/AttentionHintComponent.vue
spx-gui/src/components/editor/code-editor/ui/features/completion-menu/CompletionMenuComponent.vue
spx-gui/src/components/editor/code-editor/ui/features/inlay-hint/InlayHintComponent.vue

this pr is about add new features to compiler `getTypes`, `getTokenDetail`, add comment for classname `.view-line`, class `style-sheet-content`

feat(spx-gui): add new compiler features

---

spx-gui/src/components/editor/code-editor/CodeEditor.vue
spx-gui/src/components/editor/code-editor/code-text-editor/CodeTextEditor.vue
spx-gui/src/components/editor/sprite/SpriteEditor.vue
spx-gui/src/components/editor/stage/StageEditor.vue
spx-gui/src/models/sprite.ts
spx-gui/src/models/stage.ts

Save & resume editor state (scroll position, ...) when switching code files.

Save editor state

---

spx-gui/src/components/editor/sound/SoundPlayer.vue
spx-gui/src/components/editor/sound/waveform/WaveformPlayer.vue
spx-gui/src/components/project/runner/ProjectRunner.vue
spx-gui/src/utils/player-registry.ts

Avoid audios playing simultaneously

---

tools/compiler/internal/base.go
tools/compiler/internal/completion.go
tools/compiler/internal/definition.go
tools/compiler/internal/diagnostics.go
tools/compiler/js.go
tools/compiler/static/index.js
tools/compiler/static/parent.html

feat: add tokens get.
feat: add struct name to definition item.
feat: change the definition.
feat: add token id into completion item.

feat`WASM Compiler`: Add some things.

---

spx-backend/init.sql
spx-backend/internal/controller/llm.go
spx-backend/internal/controller/llm_test.go
spx-backend/internal/llm/llm.go
spx-gui/src/apis/llm.ts
spx-gui/src/components/editor/code-editor/CodeEditor.vue
spx-gui/src/components/editor/code-editor/chat-bot.ts
spx-gui/src/components/editor/code-editor/coordinators/index.ts
spx-gui/src/components/editor/code-editor/ui/features/chat-bot/ChatBotModalComponent.vue
spx-gui/src/components/editor/code-editor/ui/features/chat-bot/ChatBubble.vue

feat: Frontend AI fix and add task support
fix: Backend backend to support LLM side `Meta-Llama-3.1-8B-Instruct`. 
- 现在有一个问题这个8b的模型，没法每次都准确的输出json格式的内容，产生错误的概率还挺高，而且没法使用强制json模式。

feat`SPX Backend`: LLM support.

---

tools/compiler/.gitignore
tools/compiler/internal/base.go
tools/compiler/internal/completion.go
tools/compiler/internal/definition.go
tools/compiler/internal/diagnostics.go
tools/compiler/internal/setups.go
tools/compiler/internal/types.go
tools/compiler/static/index.js
tools/compiler/static/parent.html

- Multiply file support.
- Rename.

Fix`WASM Compiler`: Multiply file support.

---

spx-gui/src/components/editor/code-editor/ui/features/hover-preview/HoverPreviewComponent.vue
spx-gui/src/components/editor/code-editor/ui/features/hover-preview/hover-preview.ts

this pr is about when showing documents card will auto collapse and expand in hover

feat(spx-gui): collapse document card

---

spx-gui/src/components/project/runner/IframeDisplay.vue
spx-gui/src/components/project/runner/ProjectRunner.vue

- **Show loading spinner for runner while the project is loading**
- **move outing out of IframeDisplay**

Show loading spinner for runner while the project is loading

---

spx-gui/src/apis/llm.ts
spx-gui/src/components/editor/code-editor/EditorUI.ts
spx-gui/src/components/editor/code-editor/chat-bot.ts
spx-gui/src/components/editor/code-editor/coordinators/index.ts
spx-gui/src/components/editor/code-editor/ui/features/attention-hint/AttentionHintComponent.vue

this pr is about fix attention hint can not match current file error, fix EditorUI not correct dispose provider cause memory leak when hmr, and code style formmat

fix(spx-gui): fix attentionHint  not filter diagnostics in different code page.

---

spx-gui/src/components/editor/code-editor/compiler.ts
spx-gui/src/components/editor/code-editor/coordinators/hoverProvider.ts
spx-gui/src/components/editor/code-editor/coordinators/index.ts
tools/compiler/internal/completion.go
tools/compiler/internal/definition.go
tools/compiler/internal/inlayHint.go
tools/compiler/internal/utils.go
tools/compiler/js.go
tools/compiler/main.go

* Fix some compiler runtime panic (nil pointer) issue
* Optimize compiler panic debugging
* Fix `findDefinition` issue with multiple files

Fix code editor issues

---

spx-gui/src/assets/compiler/index.html
spx-gui/src/components/editor/code-editor/CodeEditor.vue
spx-gui/src/components/editor/code-editor/compiler.ts
spx-gui/src/components/editor/code-editor/coordinators/hoverProvider.ts
spx-gui/src/components/editor/code-editor/coordinators/index.ts
spx-gui/src/components/editor/code-editor/document.ts
spx-gui/src/components/editor/code-editor/tokens/gop.ts
spx-gui/src/components/editor/code-editor/tokens/index.ts
spx-gui/src/components/editor/code-editor/tokens/spx.ts
spx-gui/src/components/editor/code-editor/tokens/types.ts
spx-gui/src/components/editor/code-editor/ui/CodeEditorUI.vue
spx-gui/src/components/editor/code-editor/ui/EditorSidebar.vue
spx-gui/src/components/editor/code-editor/ui/ToolItem.vue

this pr is about implement `inputAssistantProvider`, implement `getTokenDetail`, `getTokensDetail`

refacotr(spx-gui): refactor `inputAssistantProvider`

---

spx-backend/internal/controller/asset.go
spx-backend/internal/model/milvus.go
spx-backend/milvusInit.go
spx-gui/src/apis/aigc.ts
spx-gui/src/apis/asset.ts
spx-gui/src/components/asset/index.ts
spx-gui/src/components/asset/library/AssetRenameModal.vue
spx-gui/src/components/asset/library/ai/AIPreviewModal.vue

Previously, the milvus vector database only had query data. As a result, no content is returned from the search suggestions. This PR adds adding assets to milvus and fixes some milvus configuration issues.
- Add IVF flat index creation for asset collection
- Update distance metric type in SearchByVector function
- Add asset to Milvus database when adding asset to asset library

Fix search suggestions

---

spx-gui/src/components/asset/index.ts
spx-gui/src/components/asset/preprocessing/PreprocessModal.vue
spx-gui/src/components/editor/code-editor/EditorUI.ts
spx-gui/src/components/editor/code-editor/coordinators/hoverProvider.ts
spx-gui/src/components/editor/code-editor/ui/EditorSidebar.vue
spx-gui/src/components/editor/code-editor/ui/features/completion-menu/CompletionMenuComponent.vue
spx-gui/src/components/editor/code-editor/ui/features/completion-menu/completion-menu.ts
spx-gui/src/components/editor/code-editor/ui/features/hover-preview/AudioPreview.vue
spx-gui/src/components/editor/code-editor/ui/features/hover-preview/HoverPreviewComponent.vue
spx-gui/src/components/editor/code-editor/ui/features/hover-preview/hover-preview.ts

this pr is about refactor `AudioPreview.vue` props from `{ src: string }` info `{ file: File }` and update related types

refactor(spx-gui): refactor Audio player props

---

spx-gui/src/components/editor/EditorContextProvider.vue
spx-gui/src/components/editor/ProjectEditor.vue
spx-gui/src/components/editor/code-editor/CodeEditor.vue
spx-gui/src/components/editor/code-editor/coordinators/index.ts
spx-gui/src/components/editor/code-editor/runtime.ts
spx-gui/src/components/editor/panels/DebugInfoPanels.vue
spx-gui/src/components/editor/preview/DebugPreview.vue
spx-gui/src/components/editor/preview/EditorPreview.vue
spx-gui/src/models/project/index.ts
spx-gui/src/models/runtime.ts

- Add a debug panel.
- Make debug info clickable.
- Add error info list into editor context provider.

feat`SPX Frontend`:Add debug mode.

---

spx-gui/src/components/SigninCallback.vue

https://github.com/goplus/casdoor/pull/3

consume language from login page

---

spx-gui/src/components/community/CenteredWrapper.vue
spx-gui/src/components/community/TopNav.vue
spx-gui/src/pages/community/explore.vue
spx-gui/src/pages/community/home.vue
spx-gui/src/pages/community/index.vue
spx-gui/src/pages/community/projects.vue
spx-gui/src/pages/community/user/index.vue

Layout for community pages

---

spx-backend/cmd/spx-backend/util.go
spx-gui/src/components/community/user/FollowButton.vue
spx-gui/src/components/community/user/UserHeader.vue

fix(community/user/UserHeader.vue): display `FollowButton` only when not viewing the current user

---

spx-gui/src/apis/common/client.ts
spx-gui/src/apis/user.ts

* Avoid parsing body of 204 response
* Fix params to list user

Fix api calling issues

---

spx-backend/internal/controller/project.go
spx-backend/internal/controller/project_test.go

```
spx-backend/util.go:69: failed to handle request [DELETE /project/nighca/Weather2]: failed to delete project: Error 1054 (42S22): Unknown column 'user_project_relationship.project_id' in 'where clause'
spx-backend/util.go:69: failed to handle request [POST /project]: failed to create project: Error 1054 (42S22): Unknown column 'project_release.id' in 'where clause'
```

fix(spx-backend): work around GORM's missing `JOIN` support in updates

---

spx-gui/src/components/community/user/FollowButton.vue
spx-gui/src/components/project/ProjectItem.vue

fix: check `isFollowing` and `isLiking` only when logged in

---

spx-gui/src/pages/community/project.vue

fix: check `isLiking` only when signed in

---

spx-backend/cmd/spx-backend/gop_autogen.go
spx-backend/cmd/spx-backend/post_project_#owner_#name_view.yap
spx-backend/internal/controller/project.go
spx-backend/internal/controller/project_test.go
spx-gui/src/apis/project.ts
spx-gui/src/pages/community/project.vue

This is a follow-up to #1003.
Fixes #1007

refactor: increment view count when visiting project page

---

docs/openapi.yaml
spx-backend/cmd/spx-backend/delete_asset_#id.yap
spx-backend/cmd/spx-backend/delete_project_#owner_#name.yap
spx-backend/cmd/spx-backend/delete_project_#owner_#name_liking.yap
spx-backend/cmd/spx-backend/delete_user_#username_following.yap
spx-backend/cmd/spx-backend/get_assets_list.yap
spx-backend/cmd/spx-backend/get_project_#owner_#name_liking.yap
spx-backend/cmd/spx-backend/get_projects_list.yap
spx-backend/cmd/spx-backend/get_user_#username_following.yap
spx-backend/cmd/spx-backend/get_util_upinfo.yap
spx-backend/cmd/spx-backend/gop_autogen.go
spx-backend/cmd/spx-backend/middleware.go
spx-backend/cmd/spx-backend/post_aigc_matting.yap
spx-backend/cmd/spx-backend/post_asset.yap
spx-backend/cmd/spx-backend/post_project-release.yap
spx-backend/cmd/spx-backend/post_project.yap
spx-backend/cmd/spx-backend/post_project_#owner_#name_liking.yap
spx-backend/cmd/spx-backend/post_project_#owner_#name_view.yap
spx-backend/cmd/spx-backend/post_user_#username_following.yap
spx-backend/cmd/spx-backend/put_asset_#id.yap
spx-backend/cmd/spx-backend/put_project_#owner_#name.yap
spx-backend/cmd/spx-backend/put_user.yap
spx-backend/cmd/spx-backend/util.go
spx-backend/internal/controller/asset.go
spx-backend/internal/controller/asset_test.go
spx-backend/internal/controller/project.go
spx-backend/internal/controller/project_release_test.go
spx-backend/internal/controller/project_test.go
spx-backend/internal/controller/user.go
spx-backend/internal/controller/user_test.go

This also improves authentication-related naming for better readability.
Fixes #1016

refactor(spx-backend): refine visibility checks in `ListProjects` and `ListAssets`

---

spx-backend/internal/model/model.go
spx-backend/internal/model/project.go
spx-backend/internal/model/user.go

Since MySQL doesn't support partial index with `WHERE` clause, use trigger to ensure uniqueness for non-deleted records.

refactor(spx-backend): use trigger to simulate partial unique index

---

spx-gui/src/apis/project.ts
spx-gui/src/components/project/ProjectCreateModal.vue
spx-gui/src/models/common/cloud.ts
spx-gui/src/pages/community/project.vue
spx-gui/src/pages/editor/index.vue
spx-gui/src/router.ts
spx-gui/src/utils/route.ts

Close #1025 
* Fix publishing issue of projects without thumbnail
* Use default thumbnail image when creating project

Fix publishing issue of projects without thumbnail

---

spx-gui/src/pages/community/home.vue

Design not finished yet, hide it temporarily. Continued work tracked with https://github.com/goplus/builder/issues/1028.

Hide my-projects for guest users

---

spx-gui/src/components/editor/code-editor/code-text-editor/tools/gop.ts
spx-gui/src/components/ui/UIDropdown.vue

* Close #1039 
* Fix `UIDropdown` offset issue when placed on top

Update snippet for iteration

---

spx-gui/src/stores/user/signed-in.ts

Optimize sign-in redirection

---

spx-gui/src/components/editor/code-editor/code-text-editor/tools/index.ts
spx-gui/src/components/editor/code-editor/code-text-editor/tools/spx.ts

* Close #1052
* Merge tools "Move" & "Position"

Expose spx `turn` in code editor

---

spx-gui/src/components/community/TextView.vue
spx-gui/src/components/community/project/ReleaseHistory.vue
spx-gui/src/components/community/user/UserHeader.vue
spx-gui/src/components/community/user/UserItem.vue
spx-gui/src/pages/community/project.vue

Preserve line breaks in text content, which includes:
* Description of user
* Description and instructions of project
* Description of project-release
updates #1060

Preserve line breaks in text content

---

spx-gui/src/components/editor/code-editor/code-text-editor/tools/index.ts
spx-gui/src/components/editor/code-editor/code-text-editor/tools/spx.ts

Add widget related tools for `CodeEditor`

---

spx-gui/src/components/editor/sprite/animation/AnimationSettings.vue
spx-gui/src/components/ui/UIDropdown.vue
spx-gui/src/components/ui/modal/UIDropdownModal.vue

Dropdown interactions with key pressing

---

spx-gui/src/components/community/user/UserItem.vue
spx-gui/src/components/editor/code-editor/code-text-editor/tools/index.ts
spx-gui/src/components/editor/code-editor/code-text-editor/tools/spx.ts
spx-gui/src/components/editor/preview/EditorPreview.vue
spx-gui/src/components/editor/sprite/animation/AnimationSettings.vue
spx-gui/src/components/project/runner/IframeDisplay.vue
spx-gui/src/components/project/runner/ProjectRunner.vue
spx-gui/src/components/project/runner/RunnerContainer.vue
spx-gui/src/components/ui/UIDropdown.vue
spx-gui/src/components/ui/modal/UIDropdownModal.vue
spx-gui/src/models/project/index.test.ts
spx-gui/src/pages/community/project.vue
spx-gui/src/widgets/spx-runner/SpxRunner.ce.vue

* Related project: https://github.com/orgs/goplus/projects/6/views/1

Release v1.5.3

---

docs/product/code-editor.md
docs/product/code-editor.zh.md

Product design doc for code-editor

---

spx-gui/src/components/editor/code-editor/CodeEditor.vue
spx-gui/src/components/editor/code-editor/common.ts
spx-gui/src/components/editor/code-editor/document-base.ts
spx-gui/src/components/editor/code-editor/document-base/gop.ts
spx-gui/src/components/editor/code-editor/document-base/index.ts
spx-gui/src/components/editor/code-editor/document-base/spx.ts
spx-gui/src/components/editor/code-editor/ui/APIReference.vue
spx-gui/src/components/editor/code-editor/ui/CodeEditorUI.vue
spx-gui/src/components/editor/code-editor/ui/MarkdownView.vue
spx-gui/src/components/editor/code-editor/ui/api-reference.ts
spx-gui/src/components/editor/code-editor/ui/completion.ts
spx-gui/src/components/editor/code-editor/ui/copilot.ts
spx-gui/src/components/editor/code-editor/ui/hover.ts
spx-gui/src/components/editor/code-editor/ui/index.ts
spx-gui/src/utils/disposable.ts

Based on #1091.
* Module `DocumentBase` for code editor, close #1092
* Draft for `APIReference`

Module `DocumentBase` for code editor

---

tools/spxls/internal/server/diagnostic.go
tools/spxls/internal/server/diagnostic_test.go
tools/spxls/internal/server/server.go
tools/spxls/internal/server/spx.go
tools/spxls/internal/server/utils.go
tools/spxls/internal/vfs/mapfs_test.go

feat(tools/spxls): implement spx resource reference check

---

spx-gui/.prettierignore
spx-gui/src/components/editor/code-editor/CodeEditor.vue
spx-gui/src/components/editor/code-editor/common.ts
spx-gui/src/components/editor/code-editor/ui/CodeEditorUI.vue
spx-gui/src/components/editor/code-editor/ui/MonacoEditor.vue
spx-gui/src/components/editor/code-editor/ui/common.ts
spx-gui/src/components/editor/code-editor/ui/completion/CompletionCard.vue
spx-gui/src/components/editor/code-editor/ui/completion/CompletionItem.vue
spx-gui/src/components/editor/code-editor/ui/completion/CompletionItemDetail.vue
spx-gui/src/components/editor/code-editor/ui/completion/CompletionUI.vue
spx-gui/src/components/editor/code-editor/ui/completion/fuzzy/README.md
spx-gui/src/components/editor/code-editor/ui/completion/fuzzy/char-code.ts
spx-gui/src/components/editor/code-editor/ui/completion/fuzzy/index.ts
spx-gui/src/components/editor/code-editor/ui/completion/fuzzy/strings.ts
spx-gui/src/components/editor/code-editor/ui/completion/index.ts
spx-gui/src/components/editor/code-editor/ui/context-menu.ts
spx-gui/src/components/editor/code-editor/ui/copilot/CopilotInput.vue
spx-gui/src/components/editor/code-editor/ui/hover/index.ts
spx-gui/src/components/editor/code-editor/ui/index.ts
spx-gui/src/components/editor/code-editor/ui/markdown/CodeLink.vue
spx-gui/src/components/editor/code-editor/ui/markdown/index.ts
spx-gui/src/components/editor/code-editor/ui/resource-reference.ts
spx-gui/src/components/editor/code-editor/ui/text-document.ts

Completion-related user interaction for code editor

---

tools/spxls/internal/server/compile.go
tools/spxls/internal/server/def.go
tools/spxls/internal/server/def_test.go
tools/spxls/internal/server/diagnostic_test.go
tools/spxls/internal/server/document_test.go
tools/spxls/internal/server/protocol.go
tools/spxls/internal/server/rename_test.go
tools/spxls/internal/server/server.go
tools/spxls/internal/server/utils.go

feat(tools/spxls): implement `textDocument/{declaration,definition,typeDefinition,implementation,references}`

---

spx-gui/src/components/editor/code-editor/document-base/spx.ts
tools/spxls/internal/server/command.go
tools/spxls/internal/server/command_test.go
tools/spxls/internal/server/compile.go
tools/spxls/internal/server/protocol.go
tools/spxls/internal/server/util.go
tools/spxls/internal/vfs/mapfs.go

close #1142.
* Fix `innermostScopeAt` for position in trailing empty lines of sprite code
* Ensure `MapFS.ReadDir` result stable
* `OverloadIndex` -> `OverloadId`
* Add some missing definitions in `document-base`

Debug api-reference

---

spx-gui/src/components/asset/index.ts
spx-gui/src/components/common/RenameModal.vue
spx-gui/src/components/editor/code-editor/FormatButton.vue
spx-gui/src/components/editor/code-editor/code-editor.ts
spx-gui/src/components/editor/code-editor/common.ts
spx-gui/src/components/editor/code-editor/context.ts
spx-gui/src/components/editor/code-editor/document-base/index.ts
spx-gui/src/components/editor/code-editor/lsp/index.ts
spx-gui/src/components/editor/code-editor/ui/CodeEditorUI.vue
spx-gui/src/components/editor/code-editor/ui/api-reference/APIReferenceUI.vue
spx-gui/src/components/editor/code-editor/ui/api-reference/index.ts
spx-gui/src/components/editor/code-editor/ui/code-editor-ui.ts
spx-gui/src/components/editor/code-editor/ui/common.ts
spx-gui/src/components/editor/code-editor/ui/context-menu/index.ts
spx-gui/src/components/editor/code-editor/ui/formatting.ts
spx-gui/src/components/editor/code-editor/ui/hover/index.ts
spx-gui/src/components/editor/preview/EditorPreview.vue
spx-gui/src/models/common/asset-name.ts
spx-gui/src/utils/spx/highlighter.ts
spx-gui/src/utils/spx/index.ts
tools/spxls/internal/server/command.go
tools/spxls/internal/server/rename.go
tools/spxls/internal/server/rename_test.go

LS integration for Rename & Formatting

---

docs/openapi.yaml

Add API `/copilot/message`

---

spx-gui/src/components/editor/code-editor/document-base/gop.ts
spx-gui/src/components/editor/code-editor/ui/CodeEditorCard.vue
spx-gui/src/components/editor/code-editor/ui/markdown/ResourcePreview.vue
spx-gui/src/components/editor/code-editor/ui/resource-reference/selector/ResourceSelector.vue
spx-gui/src/components/editor/code-editor/ui/resource/AnimationItem.vue
spx-gui/src/components/editor/code-editor/ui/resource/BackdropItem.vue
spx-gui/src/components/editor/code-editor/ui/resource/CostumeItem.vue
spx-gui/src/components/editor/code-editor/ui/resource/ResourceItem.vue
spx-gui/src/components/editor/code-editor/ui/resource/SoundItem.vue
spx-gui/src/components/editor/code-editor/ui/resource/SpriteItem.vue
spx-gui/src/components/editor/code-editor/ui/resource/WidgetItem.vue
spx-gui/src/components/ui/block-items/UIBackdropItem.vue
spx-gui/src/components/ui/block-items/UIBlockItem.vue
spx-gui/src/components/ui/block-items/UIEditorBackdropItem.vue
spx-gui/src/components/ui/block-items/UIEditorSoundItem.vue
spx-gui/src/components/ui/block-items/UIEditorSpriteItem.vue
spx-gui/src/components/ui/block-items/UIEditorWidgetItem.vue
spx-gui/src/components/ui/block-items/UISoundItem.vue
spx-gui/src/components/ui/block-items/UISpriteItem.vue
spx-gui/src/components/ui/menu/UIMenu.vue
spx-gui/src/components/ui/menu/UIMenuGroup.vue
spx-gui/src/components/ui/menu/UIMenuItem.vue

close #1192.
- New style Context Menu 
- Editor layer with border/box-shadow 
- Non-interactive Resource Preview in Hover Card

UI details for code editor

---

spx-gui/src/components/asset/index.ts
spx-gui/src/components/asset/library/AssetAddModal.vue
spx-gui/src/components/common/RenameModal.vue
spx-gui/src/components/editor/code-editor/FormatButton.vue
spx-gui/src/components/editor/code-editor/code-editor.ts
spx-gui/src/components/editor/code-editor/common.ts
spx-gui/src/components/editor/code-editor/context.ts
spx-gui/src/components/editor/code-editor/document-base/spx/index.ts
spx-gui/src/components/editor/code-editor/lsp/index.ts
spx-gui/src/components/editor/code-editor/ui/CodeEditorUI.vue
spx-gui/src/components/editor/preview/EditorPreview.vue
spx-gui/src/components/ui/UIButton.vue
spx-gui/src/components/ui/dialog/UIConfirmDialog.vue
spx-gui/src/utils/utils.test.ts
spx-gui/src/utils/utils.ts
tools/spxls/internal/server/command.go
tools/spxls/internal/server/rename.go

* Allow renaming when error diagnostics exist, close #1206
* Focus confirm-button in `UIConfirmDialog` automatically
* Allow running project when error diagnostics exist

Error diagnostics handling for renaming, formating & running

---

spx-gui/src/components/project/ProjectCreateModal.vue

fix(ProjectCreateModal): display correct remix title instead of `[object Object]`

---

tools/spxls/internal/server/compile.go
tools/spxls/internal/server/definition.go
tools/spxls/internal/server/definition_test.go
tools/spxls/internal/server/diagnostic_test.go
tools/spxls/internal/server/document_test.go
tools/spxls/internal/server/format.go
tools/spxls/internal/server/format_test.go
tools/spxls/internal/server/reference.go
tools/spxls/internal/server/rename.go
tools/spxls/internal/server/rename_test.go
tools/spxls/internal/server/spx_definition.go
tools/spxls/internal/server/util.go

Updates #1199
- https://github.com/goplus/builder/issues/1199#issuecomment-2579274294
- https://github.com/goplus/builder/issues/1199#issuecomment-2579281650
- https://github.com/goplus/builder/issues/1199#issuecomment-2579290223
- https://github.com/goplus/builder/issues/1199#issuecomment-2579313694
- https://github.com/goplus/builder/issues/1199#issuecomment-2586158276

fix(tools/spxls): resolve issues with LS functionality

---

spx-gui/src/components/editor/panels/ConsolePanel.vue
spx-gui/src/components/editor/preview/InPlaceRunner.vue
tools/ispx/go.mod
tools/ispx/go.sum
tools/ispx/main.go

feat(code-editor): support source location navigation for `println` messages

---

tools/spxls/go.sum
tools/spxls/internal/server/command.go
tools/spxls/internal/server/command_test.go
tools/spxls/internal/server/compile.go
tools/spxls/internal/server/completion.go
tools/spxls/internal/server/hover_test.go
tools/spxls/internal/server/server.go
tools/spxls/internal/server/util.go

Updates #1199
- https://github.com/goplus/builder/issues/1199#issuecomment-2588558346
- https://github.com/goplus/builder/issues/1199#issuecomment-2588560243

fix(tools/spxls): support array resource references and handle EOF

---

tools/spxls/internal/server/compile.go
tools/spxls/internal/server/completion.go
tools/spxls/internal/server/definition.go
tools/spxls/internal/server/definition_test.go
tools/spxls/internal/server/format.go
tools/spxls/internal/server/format_test.go
tools/spxls/internal/server/reference.go
tools/spxls/internal/server/spx_definition.go

Updates #1199:
- https://github.com/goplus/builder/issues/1199#issuecomment-2597844883

fix(tools/spxls): improve definition handling and code formatting

---

spx-gui/src/components/editor/code-editor/context.ts
spx-gui/src/utils/spx/default-light-theme.json
spx-gui/src/utils/spx/gop-tm-language.json
spx-gui/src/utils/spx/highlighter.ts

* Update theme for code highlighting, close #1240, #1246.
* Fix extra-padding issue when rendering selection in editor
* Fix code highlighting for commands with
- negative number as parameter
- no parameter while with trailing comment
- slice literal as parameter

Update theme for code highlighting

---

tools/spxls/internal/server/compile.go
tools/spxls/internal/server/document_test.go
tools/spxls/internal/server/rename_test.go
tools/spxls/internal/server/util.go

refactor(tools/spxls): improve resource reference inspecting

---

tools/spxls/client.ts

Remove unnecessary logs for LS

---

tools/ispx/main.go
tools/spxls/main.go

fix(tools): add js/wasm build tag to resolve `syscall/js` importing error

---

tools/ispx/pkg/github.com/goplus/spx/export.go

chore(tools/ispx): complete spx upgrade with `go generate`

---

spx-gui/src/components/editor/code-editor/ui/completion/CompletionItem.vue
spx-gui/src/components/editor/code-editor/ui/completion/index.ts
spx-gui/src/models/animation.ts
tools/spxls/internal/server/completion.go
tools/spxls/internal/server/spx_resource.go

* Fix style for long completion items, close #1249.
* Improve completion for resource name
- Add `Documentation` (resource preview) for spx resource completion items
- Trigger completion on `"`

Completion details optimization

---

spx-gui/src/components/editor/code-editor/ui/markdown/CodeView.vue

Fix `CodeChange` background

---

tools/spxls/internal/server/command.go
tools/spxls/internal/server/command_test.go
tools/spxls/internal/server/compile.go
tools/spxls/internal/server/completion.go
tools/spxls/internal/server/completion_test.go

refactor(tools/spxls): hide spx event handler APIs inside handler callbacks

---

spx-gui/src/components/asset/library/SpriteItem.vue
spx-gui/src/components/asset/scratch/SpriteItem.vue
spx-gui/src/components/common/CostumesAutoPlayer.vue
spx-gui/src/components/common/CostumesPlayer.vue
spx-gui/src/components/editor/code-editor/ui/markdown/ResourcePreview.vue
spx-gui/src/components/editor/code-editor/ui/resource/ResourceItem.vue
spx-gui/src/components/editor/sprite/AnimationItem.vue
spx-gui/src/components/editor/sprite/SpriteItem.vue
spx-gui/src/components/editor/sprite/animation/AnimationPlayer.vue
spx-gui/src/models/animation.ts
spx-gui/src/models/costume.ts
spx-gui/src/models/sprite.ts
spx-gui/src/utils/dom.ts
spx-gui/src/utils/utils.ts

Based on #1289, close #1138.
* Component `CostumesPlayer` & `CostumesAutoPlayer`
* Refactor `AnimationPlayer` with `CostumesPlayer`
* Use `CostumesAutoPlayer` in `SpriteItem`s & `AnimationItem`s to offer animation preview

Animation preview in sprite / animation block

---

spx-gui/src/components/editor/code-editor/code-editor.ts
spx-gui/src/components/editor/code-editor/ui/api-reference/index.ts

Implement basic fallback logic for API Reference items. Close #1300.

Optimize APIReference loading

---

spx-gui/src/components/editor/code-editor/code-editor.ts
spx-gui/src/components/editor/code-editor/text-document.ts
spx-gui/src/components/editor/code-editor/ui/api-reference/APIReferenceItem.vue
spx-gui/src/components/editor/code-editor/ui/code-editor-ui.ts
spx-gui/src/components/editor/code-editor/ui/markdown/CodeBlock.vue

Optimize code-editor insertion

---

spx-gui/src/components/editor/code-editor/document-base/spx/index.ts

Hide spx `Sprite.move`

---

spx-gui/src/components/editor/panels/ConsolePanel.vue

Optimize scroll behavior in `ConsolePanel`

---

tools/spxls/internal/server/compile.go

fix(tools/spxls): handle potential parser panics as diagnostics

---

spx-gui/src/components/editor/panels/ConsolePanel.vue

Fix scroll check in ConsolePanel

---

.github/workflows/publish-docker-image.yml
.github/workflows/validate.yml
spx-gui/src/pages/docs/api.vue

fix: correct API base URL on `/docs/api` page

---

docs/develop/guidance/base.ts
docs/develop/guidance/feature_ListFilter.md
docs/develop/guidance/module_ListFilter.md

@nighca 寒星老师，我这里对ListFilter的接口文档进行了补充，请您Review一下

feat: Expanded step type definitions to add control over other resource

---

tools/spxls/internal/server/compile.go
tools/spxls/internal/server/diagnostic_test.go

refactor(tools/spxls): report error diagnostic for non-`main` package declarations

---

tools/spxls/internal/server/document_test.go
tools/spxls/internal/server/format.go
tools/spxls/internal/server/format_test.go

refactor(tools/spxls): move doc of single-spec var block to spec itself

---

spx-gui/src/components/common/MaskWithHighlight.vue
spx-gui/src/components/common/TagNode.vue
spx-gui/src/components/common/TagRoot.vue
spx-gui/src/utils/dom.ts
spx-gui/src/utils/tagging.ts

- 完成MaskWithHighlight组件
- 完成TagRoot、TagNode和useTag的demo（主要是给MaskWithHighlight做验证

feat: complete the Mask module and Tagging to complete the demo

---

tools/spxls/internal/server/command.go
tools/spxls/internal/server/compile.go
tools/spxls/internal/server/completion.go
tools/spxls/internal/server/definition.go
tools/spxls/internal/server/format.go
tools/spxls/internal/server/highlight.go
tools/spxls/internal/server/hover.go
tools/spxls/internal/server/hover_test.go
tools/spxls/internal/server/implementation.go
tools/spxls/internal/server/protocol.go
tools/spxls/internal/server/reference.go
tools/spxls/internal/server/reference_test.go
tools/spxls/internal/server/rename.go
tools/spxls/internal/server/signature.go
tools/spxls/internal/server/util.go

fix(tools/spxls): correct UTF-16 character offset handling in LSP positions

---

spx-gui/src/apis/common/index.ts
spx-gui/src/apis/copilot.ts
spx-gui/src/components/editor/code-editor/ui/copilot/CopilotRound.vue
spx-gui/src/components/editor/code-editor/ui/copilot/CopilotUI.vue
spx-gui/src/components/editor/panels/ConsolePanel.vue
spx-gui/src/utils/dom.ts

Follow up for #1387 :
* Fix typing issue commented in https://github.com/goplus/builder/pull/1387#discussion_r1977185465
* Fix scrolling behavior for streaming copilot result
* Fix `timeout` for streaming APIs

Optimization for streaming copilot

---

tools/spxls/internal/server/compile.go
tools/spxls/internal/server/rename_test.go

fix(tools/spxls): add missing inspection of sprite resource refs in other sprite files

---

spx-gui/src/components/editor/code-editor/code-editor.ts
spx-gui/src/components/editor/panels/ConsolePanel.vue

Fix fallback API reference items

---

spx-gui/src/components/guidance/LevelPlayer.vue

@nighca 
更新内容：
1. 关卡介绍蒙层
2. 新增视频组件 `navbar` 的跳过视频按钮
3. 完善重完本关逻辑
4. ~~关卡完成后 Project B 创建~~

feat: LevelPlayer Intro mask & Skip button & Replay & Project B create

---

spx-gui/src/apis/guidance.ts
spx-gui/src/components/common/MaskWithHighlight.vue
spx-gui/src/components/editor/common/placeholder/EditorPlaceholder.vue
spx-gui/src/components/guidance/LevelPlayer.vue
spx-gui/src/components/guidance/StepPlayer.vue

@nighca 寒星老师，我这边修复好了Mask高亮部分的事件触发。

Fix mask events

---

spx-backend/cmd/spx-backend/delete_project_#owner_#name.yap
spx-backend/cmd/spx-backend/delete_project_#owner_#name_liking.yap
spx-backend/cmd/spx-backend/get_project-release_#owner_#project_#release.yap
spx-backend/cmd/spx-backend/get_project-releases_list.yap
spx-backend/cmd/spx-backend/get_project_#owner_#name.yap
spx-backend/cmd/spx-backend/get_project_#owner_#name_liking.yap
spx-backend/cmd/spx-backend/get_projects_list.yap
spx-backend/cmd/spx-backend/gop_autogen.go
spx-backend/cmd/spx-backend/post_project_#owner_#name_liking.yap
spx-backend/cmd/spx-backend/post_project_#owner_#name_view.yap
spx-backend/cmd/spx-backend/put_project_#owner_#name.yap
spx-backend/internal/controller/controller_test.go
spx-backend/internal/controller/project.go
spx-backend/internal/controller/project_release.go
spx-backend/internal/controller/project_release_test.go
spx-backend/internal/controller/project_test.go
spx-backend/internal/controller/user.go
spx-backend/internal/controller/user_test.go
spx-backend/internal/model/user.go
spx-gui/src/apis/project-release.ts
spx-gui/src/apis/project.ts
spx-gui/src/components/project/ProjectPublishModal.vue
spx-gui/src/pages/community/project.vue

refactor: introduce `ProjectFullName` and `ProjectReleaseFullName` for safer string composition

---

spx-gui/src/components/asset/index.ts
spx-gui/src/components/asset/library/AssetLibraryModal.vue

Fix this issue by moving useEditorCtx() calling into index.ts.

fix: Repair Uncaught Error in AssetLibraryModal

---

spx-gui/src/components/guidance/step/FollowingStep.vue

@nighca 寒星老师，我这里做了些修改，麻烦您Review一下~

fix: Add watcher for slotInfo to update guide positions dynamically

---

spx-backend/internal/chat91DictCnGemini/chat91DictCnGemini.go
spx-backend/internal/controller/project.go
spx-backend/internal/controller/project_test.go
spx-backend/internal/llmprompt/check_code_prompt.md

@nighca 此pr的内容
1.现有的代码检测效果有些差，这里优化了一下prompt
2.修复了listProject存在的bug
麻烦寒星老师review

Optimize prompt words and fix listProject bugs

---

spx-gui/src/components/project/runner/v1/ProjectRunnerV1.vue
spx-gui/src/components/project/runner/v2/ProjectRunnerV2.vue
spx-gui/src/components/ui/loading/UIDetailedLoading.vue
spx-gui/src/pages/editor/index.vue
spx-gui/src/utils/progress.test.ts
spx-gui/src/utils/progress.ts

Improvement for detailed loading

---

docs/develop/guidance/feature_Tagging.md
docs/develop/guidance/module_Tagging.md

@nighca 寒星老师 我这边更新了一个Tagging的文档：添加了TagSelector的部分

Update docs for tagging: add tagSelector

---

.github/workflows/validate.yml
spx-gui/README.md
spx-gui/package.json

Enforce formatting for PR by adding check in CI.

Check format in CI

---

spx-gui/src/components/copilot/CopilotProvider.vue
spx-gui/src/components/copilot/mcp/registry.ts

fix: https://github.com/goplus/builder/issues/1563

feat(copilot): implement tool registration wait mechanism and enhance registry checks

---

.github/workflows/release.yml

Use branch `dev` instead of `main` for workflow release

---

spx-gui/.env
spx-gui/install-spx.sh

https://github.com/goplus/godot/releases/tag/spx2.0.4

Upgrade spx to v2.0.4

---

spx-gui/.env.production

chore: update API base URLs for production environment

---

spx-gui/.env
spx-gui/install-spx.sh

Related: https://github.com/goplus/godot/releases/tag/spx2.0.6

Upgrade spx to v2.0.6

---

spx-gui/src/components/editor/code-editor/code-editor.ts
spx-gui/src/components/editor/code-editor/common.ts
spx-gui/src/components/editor/code-editor/document-base/gop.ts
spx-gui/src/components/editor/code-editor/document-base/index.ts
spx-gui/src/components/editor/code-editor/document-base/spx/index.ts
spx-gui/src/components/editor/code-editor/ui/api-reference/APIReferenceItem.vue
spx-gui/src/components/editor/code-editor/ui/api-reference/APIReferenceUI.vue
spx-gui/src/components/editor/code-editor/ui/api-reference/index.ts

Re-organize API reference items & improve docs

---

spx-gui/.env
spx-gui/install-spx.sh

Related: https://github.com/goplus/godot/releases/tag/spx2.0.7

Upragde spx to v2.0.7

---

spx-gui/src/components/editor/code-editor/ui/input-helper/InputHelperUI.vue

Debug InputHelper popup when switching between sprite & stage

---

spx-backend/internal/controller/asset.go
spx-gui/src/apis/asset.ts
spx-gui/src/components/asset/library/AssetLibraryModal.vue
spx-gui/src/components/asset/library/management/AssetLibraryManagementModal.vue

fix: https://github.com/goplus/builder/issues/1619

feat(asset): add display name as an order option for listing assets

---

spx-backend/internal/copilot/gop_defs.md
spx-backend/internal/copilot/spx_defs.md
spx-gui/src/components/editor/code-editor/code-editor.ts
spx-gui/src/components/editor/code-editor/document-base/spx/index.ts
spx-gui/src/utils/spx/index.ts

Align APIs with spx2

---

docs/openapi.yaml

feat(api): add `/ai/interaction/turn`

---

spx-gui/src/components/editor/code-editor/code-editor.ts

Fix completion for inline identifier

---

spx-backend/.gitignore
spx-backend/.vscode/tasks.json
spx-backend/cmd/spx-backend/gop_autogen.go
spx-backend/cmd/spx-backend/post_ai_interaction_turn.yap
spx-backend/internal/aiinteraction/aiinteraction.go
spx-backend/internal/aiinteraction/aiinteraction_test.go
spx-backend/internal/aiinteraction/prompt.go
spx-backend/internal/aiinteraction/prompt_test.go
spx-backend/internal/aiinteraction/system_prompt.md
spx-backend/internal/aiinteraction/types.go
spx-backend/internal/controller/aiinteraction.go
spx-backend/internal/controller/aiinteraction_test.go
spx-backend/internal/controller/controller.go
spx-backend/internal/copilot/prompt.go
spx-backend/internal/copilot/types.go
spx-gui/build-wasm.sh
spx-gui/src/components/editor/code-editor/lsp/index.ts
spx-gui/src/components/project/runner/v1/IframeDisplay.vue
tools/ispx/embedded_pkgs.go
tools/ispx/go.mod
tools/ispx/main.go
tools/ispx/pkg/github.com/goplus/builder/tools/ai/export.go
tools/ispx/runner.html
tools/spxls/.gitignore
tools/spxls/build.sh
tools/spxls/go.mod
tools/spxls/index.d.ts
tools/spxls/main.go

feat(spx-backend): implement `/ai/interaction/turn`

---

spx-backend/cmd/spx-backend/gop_autogen.go
spx-backend/cmd/spx-backend/post_ai_interaction_turn.yap

refactor(spx-backend): temporarily disable auth check for AI interaction

---

spx-gui/.env
spx-gui/install-spx.sh
spx-gui/src/components/project/runner/v2/ProjectRunnerV2.vue

Related: https://github.com/goplus/godot/releases/tag/spx2.0.8

Upgrade spx to v2.0.8

---

spx-gui/src/components/copilot/mcp/McpDebugger.vue

fix: https://github.com/goplus/builder/issues/1512

feat(mcp-debugger): add i18n for mcp debugger

---

spx-gui/src/components/editor/code-editor/ui/completion/index.ts

refactor(completion): debounce `startCompletion`

---

spx-gui/src/components/editor/code-editor/lsp/index.ts

feat: add auto-restart mechanism for LS

---

spx-gui/src/components/editor/code-editor/ui/common.ts
spx-gui/src/components/editor/code-editor/ui/diagnostics/DiagnosticsUI.vue
spx-gui/src/components/editor/code-editor/ui/hover/HoverUI.vue
spx-gui/src/components/editor/code-editor/ui/inlay-hint/InlayHintUI.vue
spx-gui/src/components/editor/code-editor/ui/input-helper/InputHelperUI.vue
spx-gui/src/components/editor/code-editor/ui/input-helper/index.ts

Fix code-editor decorations flickering

---

spx-gui/src/components/editor/code-editor/code-editor.ts
spx-gui/src/components/editor/code-editor/common.ts
spx-gui/src/components/editor/code-editor/document-base/spx/index.ts
spx-gui/src/components/editor/code-editor/ui/api-reference/APIReferenceUI.vue

close #1481.
https://github.com/goplus/builder/issues/1481#issuecomment-2889330933:
> APIs like `Ask`/`Answer` are missing.
> 
> We need to check APIs again by comparing with source code of spx2 & APIs of Scratch.

Update APIReference list

---

spx-gui/src/components/project/runner/v2/ProjectRunnerV2.vue

Related spx PR: https://github.com/goplus/spx/pull/660

Update ProjectRunnerV2 due to spx2 APIs change

---

spx-gui/.env
spx-gui/install-spx.sh

Related: https://github.com/goplus/godot/releases/tag/spx2.0.10

Upgrade spx to v2.0.10

---

spx-gui/src/components/navbar/NavbarProfile.vue

Remove spx-version switch UI for non-developer mode

---

spx-gui/src/components/editor/code-editor/text-document.ts

Fix code-editor input issue with Chinese IME

---

spx-gui/.env
spx-gui/install-spx.sh

Related: https://github.com/goplus/godot/releases/tag/spx2.0.12

Upgrade spx

---

spx-backend/internal/copilot/spx_defs.md
spx-gui/src/components/editor/code-editor/code-editor.ts
spx-gui/src/components/editor/code-editor/document-base/spx/index.ts

* Add `onBackdrop` for sprite in document-base
* Remove `onAnyKey` from API References
* Update `spx_defs.md`

Update API references

---

spx-gui/.env
spx-gui/install-spx.sh

close #1738.
Related: https://github.com/goplus/spx/releases/tag/v2.0.0-beta2

Upgrade spx to v2.0.0-beta2

---

spx-gui/src/utils/query.test.ts
spx-gui/src/utils/query.ts

Fix retrying for project editor

---

spx-gui/src/components/editor/code-editor/common.ts
spx-gui/src/components/editor/code-editor/ui/CodeEditorUI.vue
spx-gui/src/components/editor/code-editor/ui/MonacoEditor.vue
spx-gui/src/components/editor/code-editor/ui/api-reference/APIReferenceItem.vue
spx-gui/src/components/editor/code-editor/ui/code-editor-ui.ts
spx-gui/src/components/editor/code-editor/ui/drop-indicator/DropIndicatorUI.vue
spx-gui/src/components/editor/code-editor/ui/drop-indicator/index.ts

Draggable API Reference

---

docs/product/authz.md
docs/product/authz.zh.md

docs: add design for Authorization System

---

docs/develop/tutorial/base.ts
docs/develop/tutorial/impl_App.ts
docs/develop/tutorial/impl_Copilot.ts
docs/develop/tutorial/impl_ProjectEditor.ts
docs/develop/tutorial/impl_Tutorial.ts
docs/develop/tutorial/index.md
docs/develop/tutorial/module_Copilot.ts
docs/develop/tutorial/module_CopilotApis.ts
docs/develop/tutorial/module_CourseApis.ts
docs/develop/tutorial/module_Radar.ts
docs/develop/tutorial/module_Spotlight.ts
docs/develop/tutorial/module_Tutorial.ts
docs/develop/tutorial/tsconfig.json
docs/product/tutorial.md
docs/product/tutorial.zh.md

Tech design for #1748.
Review at https://github.com/nighca/goplus-builder/blob/issue-1748-tech-design/docs/develop/tutorial/index.md.

Tech Design for User Tutorial

---

spx-gui/src/components/editor/code-editor/ui/input-helper/SpxDirectionInput.vue
spx-gui/src/utils/dom.ts
spx-gui/src/utils/utils.ts

- Add angle selection by dragging.
- Add angle snapping with a configurable threshold (default: 15 degrees).
Fixes #1833

feat(spx-gui): improve SpxDirectionInput interaction

---

spx-gui/src/components/editor/editor-state.test.ts
spx-gui/src/components/editor/editor-state.ts
spx-gui/src/components/editor/sprite/AnimationEditor.vue
spx-gui/src/components/editor/sprite/CostumesEditor.vue
spx-gui/src/components/editor/sprite/SpriteEditor.vue
spx-gui/src/components/editor/stage/StageEditor.vue
spx-gui/src/components/editor/stage/backdrop/BackdropsEditor.vue
spx-gui/src/components/editor/stage/widget/WidgetsEditor.vue
spx-gui/src/components/project/runner/v2/ProjectRunnerV2.vue

* Fix selection with undo/redo, close #1866.
* Adjust log level for spx runner, related to #1862
Param `logLevel` is exported in https://github.com/goplus/spx/pull/724

Fix selection with undo/redo

---

spx-gui/src/App.vue
spx-gui/src/components/copilot/HighlightLink.vue
spx-gui/src/components/ui/index.ts
spx-gui/src/main.ts
spx-gui/src/utils/spotlight/SpotlightUI.vue
spx-gui/src/utils/spotlight/anchor.svg
spx-gui/src/utils/spotlight/index.ts

Fixed #1854
- Add Spotlight feature to allow attaching a hint popover to a specified element.
- Add HighlightLink component for Markdown, rendering a clickable element that triggers the hint popover.

feat(spx-gui): introduce Spotlight and HighlightLink components

---

spx-gui/.env
spx-gui/install-spx.sh
spx-gui/src/models/sound.ts
spx-gui/src/models/sprite.ts
spx-gui/src/models/stage.ts

Related release: https://github.com/goplus/builder/releases/tag/v1.8.4

Sync main to dev

---

spx-gui/src/components/tutorials/CourseSeriesItem.vue

feat(spx-gui): adjust course series layout

---

spx-gui/src/components/copilot/CopilotUI.vue
spx-gui/src/components/navbar/NavbarProfile.vue

feat(spx-gui): finish Unsigned-in feedback for CopilotUI

---

spx-backend/internal/aiinteraction/prompt_test.go
spx-backend/internal/aiinteraction/system_prompt.md

- Restructure system prompt with clearer sections and formatting.
- Add comprehensive guidelines for AI player behavior and decision-making.
- Improve response format documentation with detailed examples and common error prevention.
- Add JSON formatting for configuration sections to improve readability.
- Enhance error handling documentation with actionable guidance.

refactor(spx-backend): enhance AI Interaction system prompt with improved formatting and guidelines

---

spx-gui/src/components/copilot/CopilotUI.vue

https://github.com/goplus/builder/pull/1903#discussion_r2250300782

Update hello word for unsigned-in user in Copilot

---

docs/openapi.yaml
spx-backend/internal/aiinteraction/aiinteraction.go
spx-backend/internal/aiinteraction/aiinteraction_test.go
spx-backend/internal/aiinteraction/archive_system_prompt.md
spx-backend/internal/aiinteraction/prompt.go
spx-backend/internal/aiinteraction/system_prompt.md
spx-backend/internal/aiinteraction/types.go
tools/ai/ai.go
tools/ai/transport.go

- Add automatic history archiving when sessions exceed threshold to manage token usage.
- Create dedicated archive system prompt template for history summarization.

feat: add archived history support for AI Interaction

---

spx-gui/src/components/copilot/CopilotRoot.vue
spx-gui/src/components/copilot/CopilotRound.vue
spx-gui/src/components/copilot/common.ts
spx-gui/src/components/copilot/custom-elements/CodeChange.vue
spx-gui/src/components/copilot/custom-elements/CodeLink.ts
spx-gui/src/components/copilot/custom-elements/PageLink.ts
spx-gui/src/components/tutorials/TutorialCourseExitLink.ts
spx-gui/src/components/tutorials/TutorialRoot.vue
spx-gui/src/components/tutorials/tutorial.ts
spx-gui/src/utils/vnode.ts

close #1890.
* Simplify coding-related tools & custom elements.
* Implement proper handling for users exiting the current learning course.

Improve coding-course support

---

spx-gui/src/components/copilot/CopilotRoot.vue
spx-gui/src/components/copilot/CopilotUI.vue
spx-gui/src/components/copilot/copilot-storage.ts
spx-gui/src/components/copilot/copilot.ts
spx-gui/src/components/copilot/tool-executor.ts
spx-gui/src/components/tutorials/TutorialRoot.vue
spx-gui/src/components/tutorials/tutorial.ts

feat(spx-gui): restore previous session after page reload

---

spx-gui/src/components/copilot/CopilotUI.vue

feat(spx-gui): delete CopilotUI trigger border style

---

spx-gui/src/pages/editor/index.vue

feat(spx-gui): prevent default behavior of Ctrl/Command+S in editor

---

docs/develop/database-migration/index.md

docs: add design for Database Migration System

---

spx-gui/src/components/ui/UIDropdownWithTooltip.vue
spx-gui/src/components/ui/UITooltip.vue

fix(spx-gui): fix the display error of "add button" in Firefox

---

spx-gui/src/components/editor/common/corner-menu-item/DuplicateMenuItem.vue
spx-gui/src/components/editor/common/index.ts
spx-gui/src/components/editor/sound/SoundItem.vue
spx-gui/src/components/editor/sprite/AnimationItem.vue
spx-gui/src/components/editor/sprite/CostumeItem.vue
spx-gui/src/components/editor/sprite/SpriteItem.vue
spx-gui/src/components/editor/stage/backdrop/BackdropItem.vue
spx-gui/src/components/editor/stage/widget/WidgetItem.vue
spx-gui/src/models/animation.test.ts
spx-gui/src/models/backdrop.test.ts
spx-gui/src/models/backdrop.ts
spx-gui/src/models/costume.test.ts
spx-gui/src/models/sound.test.ts
spx-gui/src/models/sound.ts
spx-gui/src/models/sprite.test.ts
spx-gui/src/models/sprite.ts
spx-gui/src/models/widget/monitor.ts
spx-gui/src/models/widget/widget.test.ts
spx-gui/src/models/widget/widget.ts

feat(spx-gui): provide duplicate functionality for targets such as sprites and sounds

---

spx-gui/src/components/editor/code-editor/code-editor.ts
spx-gui/src/components/editor/code-editor/context.ts
spx-gui/src/components/editor/code-editor/document-base/xgo.ts
spx-gui/src/components/editor/code-editor/ui/MonacoEditor.vue
spx-gui/src/components/editor/code-editor/ui/code-editor-ui.ts

Add iteration & condition statement in API References

---

spx-gui/src/components/copilot/CopilotInput.vue
spx-gui/src/components/copilot/CopilotRound.vue
spx-gui/src/components/copilot/CopilotUI.vue
spx-gui/src/components/tutorials/TutorialStateIndicator.vue

feat(spx-gui): copilot session style adjustment

---

spx-backend/internal/embkb/about_spx.md
spx-backend/internal/embkb/spx_apis.md
spx-backend/internal/embkb/xgo_syntax.md
spx-gui/src/components/editor/code-editor/document-base/helpers.ts
spx-gui/src/components/editor/code-editor/document-base/spx/index.ts

Update Copilot's knowledge base

---

spx-gui/src/components/editor/common/painter/paintBoard.vue
spx-gui/src/components/editor/common/painter/utils/clear-canvas.ts
spx-gui/src/components/editor/common/painter/utils/import-export-manager.ts

refactor(spx-gui): refact clear canvas function

---

spx-gui/src/components/editor/common/painter/components/text_tool.vue
spx-gui/src/components/editor/common/painter/paintBoard.vue
spx-gui/src/components/editor/common/painter/utils/delegator.ts

feat(spx-gui): add text block fuction

---

spx-gui/src/components/editor/common/painter/components/reshape_tool.vue
spx-gui/src/components/editor/common/painter/paintBoard.vue
spx-gui/src/components/editor/common/painter/utils/history-manager.ts

resolve petezhuang/builder#110

feat(spx-gui): Painter Undo/Redo function

---

spx-gui/src/components/editor/common/painter/paintBoard.vue
spx-gui/src/components/editor/common/painter/utils/canvasSize.ts

resolve petezhuang/builder#111

feat(spx-gui): new ui and layout design

---

spx-backend/cmd/spx-backend/delete_recording_#id.yap
spx-backend/cmd/spx-backend/delete_recording_#id_liking.yap
spx-backend/cmd/spx-backend/get_recording_#id.yap
spx-backend/cmd/spx-backend/get_recording_#id_liking.yap
spx-backend/cmd/spx-backend/get_recordings_list.yap
spx-backend/cmd/spx-backend/post_recording_#id_liking.yap
spx-backend/cmd/spx-backend/post_recording_#id_view.yap
spx-backend/cmd/spx-backend/post_recordings.yap
spx-backend/cmd/spx-backend/put_recording_#id.yap
spx-backend/cmd/spx-backend/xgo_autogen.go
spx-backend/internal/controller/recording.go
spx-backend/internal/model/recording.go
spx-backend/internal/model/user_recording_relationship.go

- Implemented new routes for recording functionality in the yap router.
- Added corresponding controller logic to handle recording operations.
- Created the recording model for managing recording data.

feat(recording): Add recording-related routes, controller, and model to spx-backend

---

spx-gui/src/utils/spotlight/SpotlightUI.vue
spx-gui/src/utils/spotlight/anchor.svg

feat(spx-gui): improvement the Spotlight's styling, adding show and hide animations

---

spx-gui/src/apis/common/exception.ts

feat(spx-gui): add UI feedback for quota exeeded in Copilot

---

spx-gui/src/utils/img.ts

fix(spx-gui): fix the exception in ``getSVGSize`` when there is no ``viewBox`` attribute

---

tools/ai/command.go

This replaces complex reflection-based method invocation with more performant direct interface type assertion for extracting command descriptions. The previous approach used `reflect.PointerTo` and `method.Func.Call` which causes browser hangs in Wasm environments due to the overhead of reflection method calls.

refactor(tools/ai): replace reflection method calls with interface assertion in `extractCommandSpec`

---

spx-gui/src/components/editor/common/viewer/PositionIndicator.vue
spx-gui/src/components/editor/map-editor/map-viewer/MapViewer.vue
spx-gui/src/components/editor/preview/stage-viewer/StageViewer.vue

Add PositionIndicator for MapView & StageView

---

spx-gui/src/components/editor/map-editor/MapBasicConfig.vue
spx-gui/src/components/editor/map-editor/MapPhysicsInput.vue
spx-gui/src/components/editor/map-editor/MapSizeInput.vue
spx-gui/src/components/editor/map-editor/SpriteBasicConfig.vue
spx-gui/src/components/editor/map-editor/map-viewer/MapViewer.vue
spx-gui/src/components/editor/panels/sprite/SpritesPanel.vue
spx-gui/src/components/project/runner/FullScreenProjectRunner.vue
spx-gui/src/components/ui/UIConfigProvider.vue
spx-gui/src/components/ui/index.ts
spx-gui/src/components/ui/modal/UIFullScreenModal.vue
spx-gui/src/components/ui/utils/index.ts
spx-gui/src/utils/dom.ts

Debug MapViewer

---

spx-gui/src/components/editor/common/viewer/PositionIndicator.vue

Increase delay for auto-hiding of PositionIndicator

---

spx-backend/internal/controller/algorithm.go
spx-backend/internal/controller/image_recommend.go
spx-backend/internal/controller/project_context.go
spx-backend/internal/controller/svg.go
spx-backend/internal/controller/theme.go
spx-backend/internal/svggen/svggen.go

fix(spx-backend):optimize timeout of instantSearch

---

spx-backend/.env.dev
spx-backend/cmd/spx-backend/main.yap
spx-backend/cmd/spx-backend/post_images_recommend.yap
spx-backend/cmd/spx-backend/xgo_autogen.go
spx-backend/internal/config/loader.go
spx-backend/internal/controller/algorithm.go
spx-backend/internal/controller/image_recommend.go
spx-backend/internal/controller/theme.go
spx-backend/internal/controller/theme_test.go

feat(spx-backend): optimize image recommendation and add server timeout configuration

---

spx-backend/internal/embkb/spx_apis.md
spx-gui/src/components/editor/code-editor/common.ts
spx-gui/src/components/editor/code-editor/document-base/spx/index.ts

feat: enable code completion for `spx.Value` and `spx.List` types

---

spx-gui/src/components/editor/common/painter/components/ai_search.vue
spx-gui/src/components/editor/common/painter/paintBoard.vue

Fix two bugs:  
1. Wrong AI_search style  
2. Text ref

fix(spx-gui): several bugs fix

---

spx-gui/src/components/course/management/CourseSeriesEditModal.vue

To simplify usage, especially for test purpose.

Remove retriction for order of CourseSeries

---

spx-gui/src/apis/image-recommend.ts
spx-gui/src/components/editor/code-editor/ui/input-helper/spx-color-input/SpxColorInputWithHSBA.vue
spx-gui/src/components/editor/common/painter/components/aigc/modelSelector.vue
spx-gui/src/components/editor/common/painter/components/aigc/promptEditor.vue
spx-gui/src/components/editor/common/painter/components/aigc/promptInput.vue
spx-gui/src/components/editor/common/painter/components/select_color.vue
spx-gui/src/components/editor/common/painter/paintBoard.vue

This pr contains:
1. i18n support
2. new color selector
3. all api migrates to cilent

feat(spx-gui): new color selector and i18n support

---

spx-gui/.env
spx-gui/install-spx.sh

Related spx release: https://github.com/goplus/spx/releases/tag/v2.0.0-pre.17

Upragde spx to 2.0.0-pre.17
